install node modules (interop):
  stage: install-deps
  extends:
    - .linux-vm-shell-task
  needs:
    - install node modules (incremental)
  before_script:
    - !reference [.setup, script]
  script:
    - npm i --no-audit --no-fund --prefix interop
  artifacts:
    paths:
      - interop/node_modules
    expire_in: 1 day

build interop:
  stage: build
  interruptible: true
  extends: .linux-vm-shell-task
  before_script:
    - !reference [.setup, script]
    - cd interop
  script:
    - npm run compile
  needs: 
    - install node modules (interop)
    - install node modules (incremental)
  artifacts:
    expire_in: 2 days
    paths:
      - interop/build/lib

pack interop:
  extends:
    - .npm-pack
    - .linux-vm-shell-task
  variables:
    PACKAGE_DIR: interop
  needs:
    - build interop

publish interop:
  extends: 
    - .npm-publish
    - .linux-vm-shell-task
  variables:
    PACKAGE_DIR: interop
  dependencies:
    - build interop
