/*
 * Copyright (c) 2021-2025 Huawei Device Co., Ltd.
 * Copyright (c) 2021-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef ES2PANDA_IR_ETS_BROKEN_TYPE_NODE_H
#define ES2PANDA_IR_ETS_BROKEN_TYPE_NODE_H

#include "ir/typeNode.h"

namespace ark::es2panda::ir {

/* Synthetic type node, generated by a parser, placeholder for incorrect type. */

class BrokenTypeNode : public TypeNode {
public:
    ~BrokenTypeNode() override = default;

    NO_COPY_SEMANTIC(BrokenTypeNode);
    NO_MOVE_SEMANTIC(BrokenTypeNode);

    explicit BrokenTypeNode(ArenaAllocator *const allocator) : TypeNode(AstNodeType::BROKEN_TYPE_NODE, allocator) {}

    void TransformChildren(const NodeTransformer &cb, std::string_view transformationName) override;
    void Iterate(const NodeTraverser &cb) const override;
    void Dump(ir::AstDumper *dumper) const override;
    void Dump(ir::SrcDumper *dumper) const override;
    void Compile([[maybe_unused]] compiler::PandaGen *pg) const override;
    void Compile([[maybe_unused]] compiler::ETSGen *etsg) const override;
    checker::Type *Check([[maybe_unused]] checker::TSChecker *checker) override;
    checker::Type *GetType([[maybe_unused]] checker::TSChecker *checker) override;
    checker::VerifiedType Check([[maybe_unused]] checker::ETSChecker *checker) override;
    checker::Type *GetType([[maybe_unused]] checker::ETSChecker *checker) override;

    [[nodiscard]] BrokenTypeNode *Clone(ArenaAllocator *allocator, AstNode *parent) override;

    void Accept(ASTVisitorT *v) override
    {
        v->Accept(this);
    }
};
}  // namespace ark::es2panda::ir

#endif /* ES2PANDA_IR_BROKEN_TYPE_NODE_H */
