build memo-plugin:
  stage: build
  interruptible: true
  extends:
    - .linux-vm-shell-task
  needs:
    - install node modules (arkoala)
    - install node modules (arkoala-arkts)
    - install node modules (incremental)
    - install node modules (interop)
  before_script:
    - !reference [.setup, script]
    - !reference [.setup, regenerate-plugin-api]
  script:
    - npm run compile --prefix arkoala-arkts/memo-plugin

test memo-plugin:
  stage: test
  interruptible: true
  extends:
    - .linux-vm-shell-task
  needs:
    - install node modules (arkoala)
    - install node modules (arkoala-arkts)
    - install node modules (incremental)
    - install node modules (interop)
    - <ArkTS> build incremental.abc
  before_script:
    - !reference [.setup, script]
    - !reference [.setup, regenerate-plugin-api]
    - npm run compile --prefix incremental/compat
    - npm run compile --prefix incremental/common
    - npm run compile --prefix incremental/compiler-plugin
    - npm run compile --prefix incremental/runtime
    - npm run unmemoize --prefix incremental/runtime
    - npm run compile --prefix arkoala-arkts/memo-plugin
  script:
    - npm run demo:run --prefix arkoala-arkts/memo-plugin
