/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated file by wrong_ctx_tests.rb script -- DO NOT EDIT!

#include "libabckit/include/c/abckit.h"
#include "libabckit/include/c/metadata_core.h"
#include "libabckit/include/c/extensions/arkts/metadata_arkts.h"
#include "libabckit/include/c/extensions/js/metadata_js.h"
#include "libabckit/include/c/ir_core.h"

#include "helpers/helpers.h"
#include "helpers/helpers_wrong_ctx.h"

#include <gtest/gtest.h>

namespace libabckit::test {

static auto g_isaApiDynamicImp = AbckitGetIsaApiDynamicImpl(ABCKIT_VERSION_RELEASE_1_0_0);

class LibAbcKitWrongCtxTestsIsaApiDynamicImpl1 : public ::testing::Test {};

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowIfsupernotcorrectcall,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateThrowIfsupernotcorrectcall)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateThrowIfsupernotcorrectcall);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreateasyncgeneratorobj,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateCreateasyncgeneratorobj)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCreateasyncgeneratorobj);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStthisbyname,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateStthisbyname)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStthisbyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStobjbyindex,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateWideStobjbyindex)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateWideStobjbyindex);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdobjbyname,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateLdobjbyname)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateLdobjbyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateShr2,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateShr2)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateShr2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateIsin,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateIsin)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateIsin);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdobjbyindex,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateWideLdobjbyindex)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateWideLdobjbyindex);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbynamewithnameset,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateStownbynamewithnameset)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStownbynamewithnameset);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLess,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateLess)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateLess);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetmodulenamespace,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateGetmodulenamespace)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateGetmodulenamespace);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdsuperbyvalue,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateLdsuperbyvalue)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateLdsuperbyvalue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCallthisrange,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateWideCallthisrange)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateWideCallthisrange);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDec,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateDec)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateDec);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeCallinit,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateCallruntimeCallinit)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallruntimeCallinit);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNot,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateNot)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateNot);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStglobalvar,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateStglobalvar)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStglobalvar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAdd2,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateAdd2)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateAdd2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStobjbyindex,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateStobjbyindex)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStobjbyindex);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateOr2,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateOr2)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateOr2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGreater,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateGreater)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateGreater);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStsuperbyname,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateStsuperbyname)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStsuperbyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateResumegenerator,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateResumegenerator)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateResumegenerator);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetpropiterator,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateGetpropiterator)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateGetpropiterator);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStobjbyvalue,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateStobjbyvalue)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStobjbyvalue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateMod2,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateMod2)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateMod2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeDefineprivateproperty,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateCallruntimeDefineprivateproperty)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallruntimeDefineprivateproperty);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSuspendgenerator,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateSuspendgenerator)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateSuspendgenerator);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreategeneratorobj,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl1, iCreateCreategeneratorobj)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCreategeneratorobj);
}

}  // namespace libabckit::test
