/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated file by wrong_ctx_tests.rb script -- DO NOT EDIT!

#include "libabckit/include/c/abckit.h"
#include "libabckit/include/c/metadata_core.h"
#include "libabckit/include/c/extensions/arkts/metadata_arkts.h"
#include "libabckit/include/c/extensions/js/metadata_js.h"
#include "libabckit/include/c/ir_core.h"

#include "helpers/helpers.h"
#include "helpers/helpers_wrong_ctx.h"

#include <gtest/gtest.h>

namespace libabckit::test {

static auto g_isaApiDynamicImp = AbckitGetIsaApiDynamicImpl(ABCKIT_VERSION_RELEASE_1_0_0);

class LibAbcKitWrongCtxTestsIsaApiDynamicImpl0 : public ::testing::Test {};

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallrange,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallrange)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallrange);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowUndefinedifholewithname,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateThrowUndefinedifholewithname)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateThrowUndefinedifholewithname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStrictnoteq,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateStrictnoteq)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStrictnoteq);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGreatereq,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateGreatereq)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateGreatereq);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCallrange,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateWideCallrange)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateWideCallrange);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAsyncgeneratorreject,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateAsyncgeneratorreject)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateAsyncgeneratorreject);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStmodulevar,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateStmodulevar)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStmodulevar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetiterator,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateGetiterator)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateGetiterator);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLesseq,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateLesseq)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateLesseq);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetresumemode,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateGetresumemode)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateGetresumemode);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStpatchvar,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateWideStpatchvar)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateWideStpatchvar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallargs3,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallargs3)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallargs3);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCreateobjectwithexcludedkeys,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateWideCreateobjectwithexcludedkeys)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateWideCreateobjectwithexcludedkeys);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateMul2,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateMul2)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateMul2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeNotifyconcurrentresult,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallruntimeNotifyconcurrentresult)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallruntimeNotifyconcurrentresult);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefinegettersetterbyvalue,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateDefinegettersetterbyvalue)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateDefinegettersetterbyvalue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdobjbyindex,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateLdobjbyindex)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateLdobjbyindex);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCopydataproperties,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCopydataproperties)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCopydataproperties);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeIsfalse,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallruntimeIsfalse)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallruntimeIsfalse);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTonumber,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateTonumber)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateTonumber);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAnd2,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateAnd2)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateAnd2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefineclasswithbuffer,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateDefineclasswithbuffer)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateDefineclasswithbuffer);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAsyncgeneratorresolve,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateAsyncgeneratorresolve)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateAsyncgeneratorresolve);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTonumeric,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateTonumeric)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateTonumeric);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNewobjapply,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateNewobjapply)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateNewobjapply);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateShl2,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateShl2)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateShl2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNeg,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateNeg)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateNeg);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateXor2,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateXor2)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateXor2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallthisrange,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallthisrange)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallthisrange);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbyindex,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateStownbyindex)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStownbyindex);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdobjbyvalue,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateLdobjbyvalue)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateLdobjbyvalue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateApply,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateApply)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateApply);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStmodulevar,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateWideStmodulevar)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateWideStmodulevar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTestin,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateTestin)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateTestin);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefinefunc,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateDefinefunc)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateDefinefunc);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStlexvar,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateStlexvar)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStlexvar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallargs2,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallargs2)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallargs2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallthis3,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallthis3)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallthis3);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDynamicimport,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateDynamicimport)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateDynamicimport);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowUndefinedifhole,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateThrowUndefinedifhole)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateThrowUndefinedifhole);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSupercallarrowrange,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateSupercallarrowrange)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateSupercallarrowrange);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStsuperbyvalue,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateStsuperbyvalue)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStsuperbyvalue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallthis0,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallthis0)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallthis0);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdthisbyvalue,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateLdthisbyvalue)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateLdthisbyvalue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefinepropertybyname,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateDefinepropertybyname)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateDefinepropertybyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateIstrue,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateIstrue)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateIstrue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStthisbyvalue,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateStthisbyvalue)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStthisbyvalue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowIfnotobject,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateThrowIfnotobject)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateThrowIfnotobject);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAsyncfunctionreject,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateAsyncfunctionreject)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateAsyncfunctionreject);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeDefinefieldbyindex,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallruntimeDefinefieldbyindex)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallruntimeDefinefieldbyindex);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStricteq,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateStricteq)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStricteq);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallthis1,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallthis1)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallthis1);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefinemethod,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateDefinemethod)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateDefinemethod);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateInc,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateInc)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateInc);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateIsfalse,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateIsfalse)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateIsfalse);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbyname,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateStownbyname)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStownbyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateReturn,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateReturn)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateReturn);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeDefinefieldbyvalue,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallruntimeDefinefieldbyvalue)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallruntimeDefinefieldbyvalue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAshr2,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateAshr2)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateAshr2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeTopropertykey,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallruntimeTopropertykey)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallruntimeTopropertykey);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetnextpropname,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateGetnextpropname)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateGetnextpropname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallthis2,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallthis2)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallthis2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStarrayspread,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateStarrayspread)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStarrayspread);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTrystglobalbyname,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateTrystglobalbyname)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateTrystglobalbyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbyvalue,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateStownbyvalue)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStownbyvalue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateIf,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateIf)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateIf);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateInstanceof,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateInstanceof)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateInstanceof);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAsyncfunctionresolve,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateAsyncfunctionresolve)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateAsyncfunctionresolve);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDiv2,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateDiv2)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateDiv2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStobjbyname,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateStobjbyname)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStobjbyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSupercallspread,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateSupercallspread)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateSupercallspread);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrow,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateThrow)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateThrow);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNoteq,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateNoteq)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateNoteq);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreateiterresultobj,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCreateiterresultobj)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCreateiterresultobj);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSub2,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateSub2)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateSub2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStlexvar,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateWideStlexvar)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateWideStlexvar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdprivateproperty,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateLdprivateproperty)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateLdprivateproperty);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStprivateproperty,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateStprivateproperty)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStprivateproperty);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeIstrue,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallruntimeIstrue)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallruntimeIstrue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdsuperbyname,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateLdsuperbyname)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateLdsuperbyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreateobjectwithexcludedkeys,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCreateobjectwithexcludedkeys)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCreateobjectwithexcludedkeys);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateEq,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateEq)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateEq);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSetobjectwithproto,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateSetobjectwithproto)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateSetobjectwithproto);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallarg0,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallarg0)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallarg0);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeWidestsendablevar,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallruntimeWidestsendablevar)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallruntimeWidestsendablevar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateExp,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateExp)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateExp);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAsyncfunctionawaituncaught,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateAsyncfunctionawaituncaught)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateAsyncfunctionawaituncaught);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGettemplateobject,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateGettemplateobject)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateGettemplateobject);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSetgeneratorstate,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateSetgeneratorstate)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateSetgeneratorstate);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideSupercallarrowrange,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateWideSupercallarrowrange)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateWideSupercallarrowrange);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallarg1,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallarg1)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallarg1);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeStsendablevar,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallruntimeStsendablevar)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallruntimeStsendablevar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbyvaluewithnameset,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateStownbyvaluewithnameset)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateStownbyvaluewithnameset);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetasynciterator,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateGetasynciterator)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateGetasynciterator);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeDefinesendableclass,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateCallruntimeDefinesendableclass)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateCallruntimeDefinesendableclass);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStownbyindex,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateWideStownbyindex)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateWideStownbyindex);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowConstassignment,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateThrowConstassignment)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateThrowConstassignment);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideGetmodulenamespace,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateWideGetmodulenamespace)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateWideGetmodulenamespace);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefinefieldbyname,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateDefinefieldbyname)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateDefinefieldbyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDelobjprop,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateDelobjprop)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateDelobjprop);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowIfsupernotcorrectcall,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsIsaApiDynamicImpl0, iCreateThrowIfsupernotcorrectcall)
{
    helpers_wrong_ctx::TestWrongCtx(g_isaApiDynamicImp->iCreateThrowIfsupernotcorrectcall);
}

}  // namespace libabckit::test
