/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommonConstants {
  /**
   * Max amplitude.
   */
  static readonly MAX_AMPLITUDE: number = 15000;

  /**
   * Min amplitude.
   */
  static readonly MIN_AMPLITUDE: number = 2000;

  /**
   * Column height.
   */
  static readonly COLUMN_HEIGHT: number = 100;

  /**
   * Set interval time.
   */
  static readonly SET_INTERVAL_TIME: number = 100;

  /**
   * Opacity false.
   */
  static readonly OPACITY_FALSE: number = 0;

  /**
   * Opacity true.
   */
  static readonly OPACITY_TRUE: number = 1;

  /**
   * Column width.
   */
  static readonly COLUMN_WIDTH: number = 4;

  /**
   * Height min.
   */
  static readonly HEIGHT_MIN: number = 60;

  /**
   * Height Row.
   */
  static readonly HEIGHT_ROW: number = 60;

  /**
   * Animation duration.
   */
  static readonly ANIMATION_DURATION: number = 500;

  /**
   * Audio bitrate.
   */
  static readonly AUDIO_BITRATE: number = 48000;

  /**
   * Audio channels.
   */
  static readonly AUDIO_CHANNELS: number = 2;

  /**
   * Audio sample rate.
   */
  static readonly AUDIO_SAMPLE_RATE: number = 48000;

  /**
   * Blank column.
   */
  static readonly BLANK_COLUMN: number = 20;

  /**
   * Blank row.
   */
  static readonly BLANK_ROW: number = 10;

  /**
   * Height ST.
   */
  static readonly HEIGHT_ST: number = 70;

  /**
   * Padding size.
   */
  static readonly PADDING_SIZE: number = 5;

  /**
   * Margin size.
   */
  static readonly MARGIN_SIZE: number = 5;

  /**
   * ShowToast message.
   */
  static readonly SHOW_TOAST_MESSAGE: string = '点击时间太短';

  /**
   * ShowToast duration.
   */
  static readonly SHOW_TOAST_DURATION: number = 2000;
}