/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

class A {
    constructor (this.
}

/* @@? 17:17 Error TypeError: Only abstract or native methods can't have body. */
/* @@? 17:22 Error SyntaxError: The function parameter 'this' must explicitly specify the typeAnnotation. */
/* @@? 17:22 Error SyntaxError: Unexpected token, expected ',' or ')'. */
/* @@? 17:22 Error SyntaxError: Unexpected token '.'. */
