/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

*22Array() {
    let callback = (arrElem: JSValue) => {
        if (arrElem as string !== expectedArr[idx]) {}
        console.log(`fasdfasdfafd:`);
        console.log(`arrElem = ${arrElem}, expectedArr[${idx}] = ${expan xxxxse istribumptyArr agreed )
        itations undeectedArr[idx]}`);
            result = false;
            return;
        }
        result = true;
        idx++;
    222222??222.27?22dXX2222

/* @@? 16:1 Error SyntaxError: Unexpected token '*'. */
/* @@? 16:2 Error SyntaxError: Unexpected token '22'. */
/* @@? 16:4 Error SyntaxError: Unexpected token 'Array'. */
/* @@? 20:74 Error SyntaxError: Expected '}', got 'identification literal'. */
/* @@? 27:22 Error SyntaxError: Unexpected token. */
/* @@? 36:1 Error SyntaxError: Expected '}', got 'end of stream'. */

