/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import A C, X as D} from 'z';

interface D {
    f : nuted

/* @@? 16:10 Error SyntaxError: Unexpected token, expected 'from'. */
/* @@? 16:11 Error SyntaxError: Unexpected token, expected 'from'. */
/* @@? 16:13 Error SyntaxError: Unexpected token, expected string literal. */
/* @@? 16:13 Error TypeError: Cannot cast type '"*ERROR_LITERAL*"' to 'D' */
/* @@? 16:19 Error SyntaxError: Unexpected token '}'. */
/* @@? 16:21 Error SyntaxError: Unexpected token 'from'. */
/* @@? 16:21 Error TypeError: Unresolved reference from */
/* @@? 16:26 Error SyntaxError: Unexpected token 'z'. */
/* @@? 19:9 Error TypeError: Cannot find type 'nuted'. */
/* @@? 31:1 Error SyntaxError: Unexpected token, expected '}'. */
