/*
 * Copyright (c) 2024-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


import type {StandardExportedClass as IT1, ClassForExport as IT2} from /* @@ label */"./type_binding_neg_to_export.ets"

function main () {
    let c1 = new IT1 // compile-time error: cannot create objects of type IT1
}

/* @@@ label Error TypeError: Cannot import 'StandardExportedClass', imported type imports only exported types.  */
