/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

        &&HANDLE_CALLRUNTIME_NOTIFYCONCURRENTRESULT_PREF_NONE,
        &&HANDLE_CALLRUNTIME_DEFINEFIELDBYVALUE_PREF_IMM8_V8_V8,
        &&HANDLE_CALLRUNTIME_DEFINEFIELDBYINDEX_PREF_IMM8_IMM32_V8,
        &&HANDLE_CALLRUNTIME_TOPROPERTYKEY_PREF_NONE,
        &&HANDLE_CALLRUNTIME_CREATEPRIVATEPROPERTY_PREF_IMM16_ID16,
        &&HANDLE_CALLRUNTIME_DEFINEPRIVATEPROPERTY_PREF_IMM8_IMM16_IMM16_V8,
        &&HANDLE_CALLRUNTIME_CALLINIT_PREF_IMM8_V8,
        &&HANDLE_CALLRUNTIME_DEFINESENDABLECLASS_PREF_IMM16_ID16_ID16_IMM16_V8,
        &&HANDLE_CALLRUNTIME_LDSENDABLECLASS_PREF_IMM16,
        &&HANDLE_CALLRUNTIME_LDSENDABLEEXTERNALMODULEVAR_PREF_IMM8,
        &&HANDLE_CALLRUNTIME_WIDELDSENDABLEEXTERNALMODULEVAR_PREF_IMM16,
        &&HANDLE_CALLRUNTIME_NEWSENDABLEENV_PREF_IMM8,
        &&HANDLE_CALLRUNTIME_WIDENEWSENDABLEENV_PREF_IMM16,
        &&HANDLE_CALLRUNTIME_STSENDABLEVAR_PREF_IMM4_IMM4,
        &&HANDLE_CALLRUNTIME_STSENDABLEVAR_PREF_IMM8_IMM8,
        &&HANDLE_CALLRUNTIME_WIDESTSENDABLEVAR_PREF_IMM16_IMM16,
        &&HANDLE_CALLRUNTIME_LDSENDABLEVAR_PREF_IMM4_IMM4,
        &&HANDLE_CALLRUNTIME_LDSENDABLEVAR_PREF_IMM8_IMM8,
        &&HANDLE_CALLRUNTIME_WIDELDSENDABLEVAR_PREF_IMM16_IMM16,
        &&HANDLE_CALLRUNTIME_ISTRUE_PREF_IMM8,
        &&HANDLE_CALLRUNTIME_ISFALSE_PREF_IMM8,
        &&HANDLE_CALLRUNTIME_LDLAZYMODULEVAR_PREF_IMM8,
        &&HANDLE_CALLRUNTIME_WIDELDLAZYMODULEVAR_PREF_IMM16,
        &&HANDLE_CALLRUNTIME_LDLAZYSENDABLEMODULEVAR_PREF_IMM8,
        &&HANDLE_CALLRUNTIME_WIDELDLAZYSENDABLEMODULEVAR_PREF_IMM16,
        &&HANDLE_CALLRUNTIME_SUPERCALLFORWARDALLARGS_PREF_V8,
        &&HANDLE_CALLRUNTIME_LDSENDABLELOCALMODULEVAR_PREF_IMM8,
        &&HANDLE_CALLRUNTIME_WIDELDSENDABLELOCALMODULEVAR_PREF_IMM16
