/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { City, getSideBg, MyDataSource, Style } from 'common';
import { hilog } from '@kit.PerformanceAnalysisKit';

const DOMAIN = 0x0000;

@Component
export default struct SideContent {
  @StorageLink('cityList') @Watch('cityListChange') cities: Array<City> = [];
  @StorageLink('swiperIndex') swiperIndex: number = 0;
  @Link showSideBar: boolean;
  cityList: MyDataSource<City> = new MyDataSource(this.cities);

  @Builder
  header() {
    Row() {
      Blank()
      Image($r('app.media.icon_subarea'))
        .id('cancelSubarea')
        .size({ width: 24, height: 24 })
        .objectFit(ImageFit.Contain)
        .onClick(() => {
          this.showSideBar = !this.showSideBar;
        })
    }
    .width('100%')

    Text($r('app.string.weather'))
      .fontColor(Color.White)
      .fontSize(30)
      .fontWeight(FontWeight.Medium)
      .width('100%')
    Search({ placeholder: $r('app.string.search_placeholder'), icon: '/common/images/icon_search.svg' })
      .placeholderFont({ size: 16 })
      .placeholderColor('#60FFFFFF')
      .width('100%')
      .backgroundColor($r('sys.color.container_modal_button_hover_baseboard'))
      .margin({ top: 4 })
      .borderRadius(45)
  }

  build() {
    Column({ space: Style.NORMAL_SPACE }) {
      this.header()
      List({ space: 12 }) {
        LazyForEach(this.cityList, (item: City, index: number) => {
          ListItem() {
            CityItem({ cityInfo: item, index: index })
          }
          .id('sliderCity' + index)
          .onClick(() => {
            this.swiperIndex = index;
            AppStorage.setOrCreate('swiperIndex', index);
          })
        }, (item: City, index: number) => JSON.stringify(item) + index)
      }
      .margin({ top: 8 })
      .width('100%')
      .layoutWeight(1)
    }
    .width('100%')
    .height('100%')
    .padding(Style.NORMAL_PADDING)
    .backgroundColor('#0D000000')
  }

  cityListChange() {
    this.cityList.dataArray = this.cities;
    this.cityList.notifyDataReload();
  }
}

@Component
struct CityItem {
  @StorageLink('swiperIndex') swiperIndex: number = 0;
  cityInfo?: City;
  index: number = 0;

  getResourceFile(): Resource | undefined {
    try {
      return getSideBg(this.getUIContext()
        .getHostContext()?.resourceManager.getStringSync((this.cityInfo!.weather as Resource).id) as string);
    } catch (error) {
      hilog.error(DOMAIN, 'testTag', '%{public}s',
        `getStringSync failed, error code: ${error.code}, message: ${error.message}.`);
      return undefined;
    }
  }

  build() {
    Row() {
      Text(this.cityInfo?.name)
        .fontColor(Color.White)
        .fontSize(24)
      if (this.index === 0) {
        Image($r('app.media.icon_location'))
          .size({ width: 16, height: 16 })
          .objectFit(ImageFit.Contain)
      }
      Blank()
      Column() {
        Row() {
          Text(this.cityInfo?.temp)
            .fontColor(Color.White)
            .fontWeight(Style.BIG_FONT_WEIGHT)
            .fontSize(54)
          Text($r('app.string.du'))
            .fontColor(Color.White)
            .fontSize(20)
            .margin({ bottom: 28 })
        }

        Text(this.cityInfo?.weather)
          .fontColor(Color.White)
          .fontSize(14)
      }
    }
    .width('100%')
    .height(100)
    .alignItems(VerticalAlign.Center)
    .padding(Style.NORMAL_PADDING)
    .border({
      radius: Style.NORMAL_RADIUS,
      width: 1,
      color: this.swiperIndex === this.index ? '#BBFFFFFF' : '#116ACD'
    })
    .alignItems(VerticalAlign.Center)
    .backgroundImageSize(ImageSize.Cover)
    .backgroundImage(this.getResourceFile())
  }
}
