/**
 * Breakpoint constants
 */
export class BreakpointConstants {
  /**
   * Small device
   */
  public static readonly BREAKPOINT_SM: string = 'sm';
  /**
   * Medium device
   */
  public static readonly BREAKPOINT_MD: string = 'md';
  /**
   * Large device
   */
  public static readonly BREAKPOINT_LG: string = 'lg';
  /**
   * Medium device min. width
   */
  public static readonly MIDDLE_DEVICE_WIDTH: number = 600;
  /**
   * Large device min. width
   */
  public static readonly LARGE_DEVICE_WIDTH: number = 840;
  /**
   *  Loading start height of small device
   */
  public static readonly LOADING_HEIGHT_SM: string = '60%';
  /**
   *  Loading start height of medium device
   */
  public static readonly LOADING_HEIGHT_MD: string = '60%';
  /**
   *  Loading start height of large device
   */
  public static readonly LOADING_HEIGHT_LG: string = '50%';
}