[dependencies]

[package]
  cjc-version = "0.53.4"
  compile-option = "" # other apps are also depend on this relative path
  description = "Incremental Runtime"
  link-option = ""
  name = "KoalaRuntime"
  output-type = "static"
  src-dir = ""
  target-dir = ""
  version = "0.0.1"
  package-configuration = {}
