/*
 * Copyright (c) 2024-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { double_1 } from "./ambient_const_vars.ets"
import { double_2 } from "./ambient_const_vars.ets"
import { double_3 } from "./ambient_const_vars.ets"
import { double_4 } from "./ambient_const_vars.ets"
import { double_5 } from "./ambient_const_vars.ets"

/* @@? 17:26 Error TypeError: Imported element not exported 'double_2' */
/* @@? 19:26 Error TypeError: Imported element not exported 'double_4' */