/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const weather: CityFull[] = [
  {
    "cityId": "101210101",
    "city": $r('app.string.Beijing'),
    "cityEn": "beijing",
    "country": $r('app.string.China'),
    "countryEn": "China",
    "updateTime": "2022-06-23 13:09:59",
    "data": [
      {
        "day": $r('app.string.23rd'),
        "date": "2022-06-23",
        "week": $r('app.string.Thursday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "yun",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "yun",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "yin",
        "tem": "32",
        "tem1": "35",
        "tem2": "25",
        "humidity": "40%",
        "visibility": "24km",
        "pressure": "998",
        "win": [
          $r('app.string.SouthwestWind'),
          $r('app.string.SouthwestWind')
        ],
        "winSpeed": '5-6 -> 3-4',
        "winMeter": "18km/h",
        "sunrise": "04:58",
        "sunset": "19:04",
        "air": "20",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.24th'),
        "date": "2022-06-24",
        "week": $r('app.string.Friday'),
        "wea": $r('app.string.Sunny'),
        "weaImg": "yu",
        "weaDay": $r('app.string.Sunny'),
        "weaDayImg": "yu",
        "weaNight": $r('app.string.Sunny'),
        "weaNightImg": "yu",
        "tem": "32",
        "tem1": "35",
        "tem2": "25",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthwestWind'),
          $r('app.string.SouthwestWind')
        ],
        "winSpeed": '3-4',
        "winMeter": "",
        "sunrise": "04:58",
        "sunset": "19:04",
        "air": "20",
        "airLevel": $r('app.string.Excellent'),
        "airTips": $r('app.string.airTips1'),
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [
          {
            "hours": "09",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "30",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "10",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "30",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "11",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "sunny",
            "tem": "31",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "12",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "31",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "13",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "32",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "14",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "32",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "15",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "31",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "16",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "30",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "17",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "30",
            "win": $r('app.string.NorthwestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "18",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "29",
            "win": $r('app.string.WestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "19",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "28",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "20",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "28",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "21",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "27",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "22",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "27",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "23",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "27",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "00",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "01",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "02",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "03",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "sunny",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "04",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "05",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "25",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "06",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "07",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "27",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "08",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "29",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3-4"
          },
        ],
        "index": [
          {
            "title": $r('app.string.Humidity'),
            "level": $r('app.string.42Per'),
            "desc": $r('app.string.Humidity_desc1')
          },
          {
            "title": $r('app.string.Temperature'),
            "level": $r('app.string.tem28'),
            "desc": ""
          },
          {
            "title": $r('app.string.WindForce'),
            "level": $r('app.string.Breeze'),
            "desc": $r('app.string.WindForce_desc1')
          },
          {
            "title": $r('app.string.WindDirection'),
            "level": $r('app.string.NorthWind'),
            "desc": ""
          },
          {
            "title": $r('app.string.Clothing'),
            "level": $r('app.string.TShirt'),
            "desc": $r('app.string.Clothing_desc1')
          },
          {
            "title": $r('app.string.Sport'),
            "level": $r('app.string.SportRecommended'),
            "desc": ""
          },
          {
            "title": $r('app.string.Cold'),
            "level": $r('app.string.ColdEasy'),
            "desc": $r('app.string.ColdDesc')
          },
          {
            "title": $r('app.string.UV'),
            "level": $r('app.string.UVStrong'),
            "desc": $r('app.string.UVDesc')
          }
        ]
      },
      {
        "day": $r('app.string.25th'),
        "date": "2022-06-25",
        "week": $r('app.string.Saturday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "cloudy",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "yun",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "yun",
        "tem": "34",
        "tem1": "32",
        "tem2": "26",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthWind'),
          $r('app.string.WinDesc')
        ],
        "winSpeed": "4-5 -> <3",
        "winMeter": "",
        "sunrise": "04:58",
        "sunset": "19:04",
        "air": "34",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.26th'),
        "date": "2022-06-26",
        "week": $r('app.string.Sunday'),
        "wea": $r('app.string.Rainy'),
        "weaImg": "yin",
        "weaDay": $r('app.string.Rainy'),
        "weaDayImg": "yin",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "yin",
        "tem": "36",
        "tem1": "36",
        "tem2": "27",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthWind'),
          $r('app.string.SouthWind')
        ],
        "winSpeed": "4-5",
        "winMeter": "",
        "sunrise": "04:59",
        "sunset": "19:04",
        "air": "29",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.27th'),
        "date": "2022-06-27",
        "week": $r('app.string.Monday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "yin",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "yin",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "yin",
        "tem": "36",
        "tem1": "36",
        "tem2": "26",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthWind'),
          $r('app.string.SouthWind')
        ],
        "winSpeed": "4-5",
        "winMeter": "",
        "sunrise": "04:59",
        "sunset": "19:04",
        "air": "26",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.28th'),
        "date": "2022-06-28",
        "week": $r('app.string.Tuesday'),
        "wea": $r('app.string.Sunny'),
        "weaImg": "sunny",
        "weaDay": $r('app.string.Sunny'),
        "weaDayImg": "sunny",
        "weaNight": $r('app.string.Sunny'),
        "weaNightImg": "sunny",
        "tem": "36",
        "tem1": "36",
        "tem2": "27",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthwestWind'),
          $r('app.string.SouthWind')
        ],
        "winSpeed": "4-5 -> 3-4",
        "winMeter": "",
        "sunrise": "04:59",
        "sunset": "19:04",
        "air": "38",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.29th'),
        "date": "2022-06-29",
        "week": $r('app.string.Wednesday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "cloudy",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "cloudy",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "cloudy",
        "tem": "35",
        "tem1": "35",
        "tem2": "26",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.WinDesc'),
          $r('app.string.WinDesc')
        ],
        "winSpeed": "<3",
        "winMeter": "",
        "sunrise": "05:00",
        "sunset": "19:04",
        "air": "31",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      }
    ],
    "aqi": {
      "updateTime": "13:44",
      "cityId": "101210101",
      "city": $r('app.string.Hangzhou'),
      "cityEn": "hangzhou",
      "country": $r('app.string.China'),
      "countryEn": "China",
      "air": "28",
      "airLevel": $r('app.string.Excellent'),
      "airTips": $r('app.string.airTips2'),
      "pm25": "94",
      "pm25Desc": $r('app.string.Excellent'),
      "pm10": "181",
      "pm10Desc": $r('app.string.Excellent'),
      "o3": "19",
      "o3Desc": $r('app.string.Excellent'),
      "no2": "105",
      "no2Desc": $r('app.string.Excellent'),
      "so2": "67",
      "so2Desc": $r('app.string.Excellent'),
      "co": "19",
      "coDesc": "-",
      "kouzhao": $r('app.string.MaskNeed1'),
      "yundong": $r('app.string.exercise1'),
      "waichu": $r('app.string.goingOut1'),
      "kaichuang": $r('app.string.windows1'),
      "jinghuaqi": $r('app.string.purifier1')
    }
  },
  {
    "cityId": "101210102",
    "city": $r('app.string.Shanghai'),
    "cityEn": "shanghai",
    "country": $r('app.string.China'),
    "countryEn": "China",
    "updateTime": "2022-06-23 13:09:59",
    "data": [
      {
        "day": $r('app.string.23rd'),
        "date": "2022-06-23",
        "week": $r('app.string.Thursday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "yun",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "cloudy",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "cloudy",
        "tem": "28",
        "tem1": "36",
        "tem2": "28",
        "humidity": "40%",
        "visibility": "24km",
        "pressure": "998",
        "win": [
          $r('app.string.SouthwestWind'),
          $r('app.string.SouthwestWind')
        ],
        "winSpeed": '5-6 -> 3-4',
        "winMeter": "18km/h",
        "sunrise": "04:58",
        "sunset": "19:04",
        "air": "20",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.Excellent'),
        "date": "2022-06-24",
        "week": $r('app.string.Friday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "yin",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "yin",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "yin",
        "tem": "28",
        "tem1": "32",
        "tem2": "25",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthwestWind'),
          $r('app.string.SouthwestWind')
        ],
        "winSpeed": '3-4',
        "winMeter": "",
        "sunrise": "04:58",
        "sunset": "19:04",
        "air": "32",
        "airLevel": $r('app.string.Excellent'),
        "airTips": $r('app.string.airTips3'),
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [
          {
            "hours": "08",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "29",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "09",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "30",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "10",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "30",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "11",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "31",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "12",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "31",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "13",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "32",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "14",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "32",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "15",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "31",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "16",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "30",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "17",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "30",
            "win": $r('app.string.NorthwestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "18",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "29",
            "win": $r('app.string.WestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "19",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "28",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "20",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "28",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "21",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "27",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "22",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "27",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "23",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "27",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "00",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "01",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "02",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "03",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "04",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "05",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "25",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "06",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "07",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yu",
            "tem": "27",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          }
        ],
        "index": [
          {
            "title": $r('app.string.Humidity'),
            "level": $r('app.string.45Per'),
            "desc": $r('app.string.Humidity_desc1')
          },
          {
            "title": $r('app.string.Humidity_desc1'),
            "level": $r('app.string.tem28'),
            "desc": ""
          },
          {
            "title": $r('app.string.WindForce'),
            "level": $r('app.string.Breeze'),
            "desc": $r('app.string.WindForce_desc1')
          },
          {
            "title": $r('app.string.WindDirection'),
            "level": $r('app.string.SouthWind'),
            "desc": ""
          },
          {
            "title": $r('app.string.Clothing'),
            "level": $r('app.string.TShirt'),
            "desc": $r('app.string.Clothing_desc1')
          },
          {
            "title": $r('app.string.Sport'),
            "level": $r('app.string.SportRecommended'),
            "desc": ""
          },
          {
            "title": $r('app.string.Cold'),
            "level": $r('app.string.ColdEasy'),
            "desc": $r('app.string.ColdDesc')
          },
          {
            "title": $r('app.string.UV'),
            "level": $r('app.string.Weak'),
            "desc": $r('app.string.UVDesc2')
          }
        ]
      },
      {
        "day": $r('app.string.25th'),
        "date": "2022-06-25",
        "week": $r('app.string.Saturday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "yun",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "yun",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "yun",
        "tem": "34",
        "tem1": "34",
        "tem2": "26",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthWind'),
          $r('app.string.WinDesc')
        ],
        "winSpeed": "4-5 -> <3",
        "winMeter": "",
        "sunrise": "04:58",
        "sunset": "19:04",
        "air": "34",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.26th'),
        "date": "2022-06-26",
        "week": $r('app.string.Sunday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "yin",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "yin",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "yin",
        "tem": "36",
        "tem1": "36",
        "tem2": "27",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthWind'),
          $r('app.string.SouthWind')
        ],
        "winSpeed": "4-5",
        "winMeter": "",
        "sunrise": "04:59",
        "sunset": "19:04",
        "air": "29",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.27th'),
        "date": "2022-06-27",
        "week": $r('app.string.Monday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "yin",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "yin",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "yin",
        "tem": "36",
        "tem1": "36",
        "tem2": "26",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthWind'),
          $r('app.string.SouthWind')
        ],
        "winSpeed": "4-5",
        "winMeter": "",
        "sunrise": "04:59",
        "sunset": "19:04",
        "air": "26",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.28th'),
        "date": "2022-06-28",
        "week": $r('app.string.Tuesday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "yin",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "yin",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "yin",
        "tem": "36",
        "tem1": "36",
        "tem2": "27",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthwestWind'),
          $r('app.string.SouthWind')
        ],
        "winSpeed": "4-5 -> 3-4",
        "winMeter": "",
        "sunrise": "04:59",
        "sunset": "19:04",
        "air": "38",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.29th'),
        "date": "2022-06-29",
        "week": $r('app.string.Wednesday'),
        "wea": $r('app.string.Rainy'),
        "weaImg": "yu",
        "weaDay": $r('app.string.Rainy'),
        "weaDayImg": "yu",
        "weaNight": $r('app.string.Rainy'),
        "weaNightImg": "yu",
        "tem": "35",
        "tem1": "35",
        "tem2": "26",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.WinDesc'),
          $r('app.string.WinDesc')
        ],
        "winSpeed": "<3",
        "winMeter": "",
        "sunrise": "05:00",
        "sunset": "19:04",
        "air": "31",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      }
    ],
    "aqi": {
      "updateTime": "13:44",
      "cityId": "101210102",
      "city": $r('app.string.Shanghai'),
      "cityEn": "shanghai",
      "country": $r('app.string.China'),
      "countryEn": "China",
      "air": "32",
      "airLevel": $r('app.string.Excellent'),
      "airTips": $r('app.string.airTips2'),
      "pm25": "80",
      "pm25Desc": $r('app.string.Excellent'),
      "pm10": "200",
      "pm10Desc": $r('app.string.Excellent'),
      "o3": "39",
      "o3Desc": $r('app.string.Excellent'),
      "no2": "100",
      "no2Desc": $r('app.string.Excellent'),
      "so2": "70",
      "so2Desc": $r('app.string.Excellent'),
      "co": "20",
      "coDesc": "-",
      "kouzhao": $r('app.string.MaskNeed1'),
      "yundong": $r('app.string.exercise1'),
      "waichu": $r('app.string.goingOut1'),
      "kaichuang": $r('app.string.windows1'),
      "jinghuaqi": $r('app.string.purifier1')
    }
  },
  {
    "cityId": "101210103",
    "city": $r('app.string.Guangzhou'),
    "cityEn": "guangzhou",
    "country": $r('app.string.China'),
    "countryEn": "China",
    "updateTime": "2022-06-23 13:09:59",
    "data": [
      {
        "day": $r('app.string.23rd'),
        "date": "2022-06-23",
        "week": $r('app.string.Thursday'),
        "wea": $r('app.string.Rainy'),
        "weaImg": "rain",
        "weaDay": $r('app.string.Rainy'),
        "weaDayImg": "rain",
        "weaNight": $r('app.string.Rainy'),
        "weaNightImg": "rain",
        "tem": "36",
        "tem1": "38",
        "tem2": "30",
        "humidity": '50%',
        "visibility": "24km",
        "pressure": "998",
        "win": [
          $r('app.string.SouthwestWind'),
          $r('app.string.SouthwestWind')
        ],
        "winSpeed": '5-6 -> 3-4',
        "winMeter": "18km/h",
        "sunrise": "04:58",
        "sunset": "19:04",
        "air": "40",
        "airLevel": $r('app.string.Excellent'),
        "airTips": $r('app.string.airTips4'),
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.Excellent'),
        "date": "2022-06-24",
        "week": $r('app.string.Friday'),
        "wea": $r('app.string.Rainy'),
        "weaImg": "yu",
        "weaDay": $r('app.string.Rainy'),
        "weaDayImg": "yu",
        "weaNight": $r('app.string.Rainy'),
        "weaNightImg": "yu",
        "tem": "26",
        "tem1": "30",
        "tem2": "22",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthwestWind'),
          $r('app.string.SouthwestWind')
        ],
        "winSpeed": '3-4',
        "winMeter": "",
        "sunrise": "04:58",
        "sunset": "19:04",
        "air": "27",
        "airLevel": $r('app.string.Excellent'),
        "airTips": $r('app.string.airTips5'),
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [
          {
            "hours": "08",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "29",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "09",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "30",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "10",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "30",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "11",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "31",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "12",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "31",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "13",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "32",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "14",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "32",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "15",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "31",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "16",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "30",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "17",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "30",
            "win": $r('app.string.NorthwestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "18",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "29",
            "win": $r('app.string.WestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "19",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "28",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "20",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "28",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "21",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "27",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "22",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "27",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "23",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "27",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "00",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "01",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "02",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "03",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "04",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "05",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "25",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "06",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "07",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "27",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          }
        ],
        "index": [
          {
            "title": $r('app.string.Humidity'),
            "level": $r('app.string.50Per'),
            "desc": $r('app.string.Humidity_desc1')
          },
          {
            "title": $r('app.string.Humidity_desc1'),
            "level": $r('app.string.tem27'),
            "desc": ""
          },
          {
            "title": $r('app.string.WindForce'),
            "level": $r('app.string.StrongWind'),
            "desc": $r('app.string.WindForce_desc1')
          },
          {
            "title": $r('app.string.WindDirection'),
            "level": $r('app.string.SoutheastWind'),
            "desc": ""
          },
          {
            "title": $r('app.string.Clothing'),
            "level": $r('app.string.LongSleeves'),
            "desc": $r('app.string.Clothing_desc1')
          },
          {
            "title": $r('app.string.Sport'),
            "level": $r('app.string.SportRecommended'),
            "desc": ""
          },
          {
            "title": $r('app.string.Cold'),
            "level": $r('app.string.ColdEasy'),
            "desc": $r('app.string.ColdDesc')
          },
          {
            "title": $r('app.string.UV'),
            "level": $r('app.string.Weak'),
            "desc": $r('app.string.UVDesc2')
          }
        ]
      },
      {
        "day": $r('app.string.25th'),
        "date": "2022-06-25",
        "week": $r('app.string.Saturday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "yun",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "yun",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "yun",
        "tem": "34",
        "tem1": "34",
        "tem2": "26",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthWind'),
          $r('app.string.WinDesc')
        ],
        "winSpeed": "4-5 -> <3",
        "winMeter": "",
        "sunrise": "04:58",
        "sunset": "19:04",
        "air": "34",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.26th'),
        "date": "2022-06-26",
        "week": $r('app.string.Sunday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "yin",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "yin",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "yin",
        "tem": "36",
        "tem1": "36",
        "tem2": "27",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthWind'),
          $r('app.string.SouthWind')
        ],
        "winSpeed": "4-5",
        "winMeter": "",
        "sunrise": "04:59",
        "sunset": "19:04",
        "air": "29",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.27th'),
        "date": "2022-06-27",
        "week": $r('app.string.Monday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "yin",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "yin",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "yin",
        "tem": "36",
        "tem1": "36",
        "tem2": "26",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthWind'),
          $r('app.string.SouthWind')
        ],
        "winSpeed": "4-5",
        "winMeter": "",
        "sunrise": "04:59",
        "sunset": "19:04",
        "air": "26",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.28th'),
        "date": "2022-06-28",
        "week": $r('app.string.Tuesday'),
        "wea": $r('app.string.ModerateRain'),
        "weaImg": "rain",
        "weaDay": $r('app.string.ModerateRain'),
        "weaDayImg": "rain",
        "weaNight": $r('app.string.ModerateRain'),
        "weaNightImg": "rain",
        "tem": "36",
        "tem1": "36",
        "tem2": "27",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthwestWind'),
          $r('app.string.SouthWind')
        ],
        "winSpeed": "4-5 -> 3-4",
        "winMeter": "",
        "sunrise": "04:59",
        "sunset": "19:04",
        "air": "38",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.29th'),
        "date": "2022-06-29",
        "week": $r('app.string.Wednesday'),
        "wea": $r('app.string.ModerateRain'),
        "weaImg": "rain",
        "weaDay": $r('app.string.ModerateRain'),
        "weaDayImg": "rain",
        "weaNight": $r('app.string.Rainy'),
        "weaNightImg": "yu",
        "tem": "35",
        "tem1": "35",
        "tem2": "26",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.WinDesc'),
          $r('app.string.WinDesc')
        ],
        "winSpeed": "<3",
        "winMeter": "",
        "sunrise": "05:00",
        "sunset": "19:04",
        "air": "31",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      }
    ],
    "aqi": {
      "updateTime": "13:44",
      "cityId": "101210103",
      "city": $r('app.string.Guangzhou'),
      "cityEn": "guangzhou",
      "country": $r('app.string.China'),
      "countryEn": "China",
      "air": "50",
      "airLevel": $r('app.string.Excellent'),
      "airTips": $r('app.string.airTips6'),
      "pm25": "90",
      "pm25Desc": $r('app.string.Excellent'),
      "pm10": "170",
      "pm10Desc": $r('app.string.Excellent'),
      "o3": "18",
      "o3Desc": $r('app.string.Excellent'),
      "no2": "90",
      "no2Desc": $r('app.string.Excellent'),
      "so2": "64",
      "so2Desc": $r('app.string.Excellent'),
      "co": "22",
      "coDesc": "-",
      "kouzhao": $r('app.string.MaskNeed1'),
      "yundong": $r('app.string.exercise1'),
      "waichu": $r('app.string.goingOut1'),
      "kaichuang": $r('app.string.windows1'),
      "jinghuaqi": $r('app.string.purifier1')
    }
  },
  {
    "cityId": "101210104",
    "city": $r('app.string.Tianjin'),
    "cityEn": "tianjin",
    "country": $r('app.string.China'),
    "countryEn": "China",
    "updateTime": "2022-06-23 13:09:59",
    "data": [
      {
        "day": $r('app.string.23rd'),
        "date": "2022-06-23",
        "week": $r('app.string.Thursday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "yin",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "yin",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "yin",
        "tem": "33",
        "tem1": "35",
        "tem2": "22",
        "humidity": "55%",
        "visibility": "24km",
        "pressure": "998",
        "win": [
          $r('app.string.NorthWind'),
          $r('app.string.NorthWind')
        ],
        "winSpeed": '5-6 -> 3-4',
        "winMeter": "18km/h",
        "sunrise": "04:58",
        "sunset": "19:04",
        "air": "35",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.Excellent'),
        "date": "2022-06-24",
        "week": $r('app.string.Friday'),
        "wea": $r('app.string.ModerateRain'),
        "weaImg": "yu",
        "weaDay": $r('app.string.ModerateRain'),
        "weaDayImg": "yu",
        "weaNight": $r('app.string.ModerateRain'),
        "weaNightImg": "yu",
        "tem": "32",
        "tem1": "32",
        "tem2": "25",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthwestWind'),
          $r('app.string.SouthwestWind')
        ],
        "winSpeed": "4",
        "winMeter": "",
        "sunrise": "04:58",
        "sunset": "19:04",
        "air": "30",
        "airLevel": $r('app.string.Excellent'),
        "airTips": $r('app.string.airTips7'),
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [
          {
            "hours": "08",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "29",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "09",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "30",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "10",
            "wea": $r('app.string.ModerateRain'),
            "weaImg": "yu",
            "tem": "30",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "11",
            "wea": $r('app.string.ModerateRain'),
            "weaImg": "yu",
            "tem": "31",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "12",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "31",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "13",
            "wea": $r('app.string.ModerateRain'),
            "weaImg": "yu",
            "tem": "32",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "14",
            "wea": $r('app.string.ModerateRain'),
            "weaImg": "yu",
            "tem": "32",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "15",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "31",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "16",
            "wea": $r('app.string.ModerateRain'),
            "weaImg": "yu",
            "tem": "30",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "17",
            "wea": $r('app.string.ModerateRain'),
            "weaImg": "yu",
            "tem": "30",
            "win": $r('app.string.NorthwestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "18",
            "wea": $r('app.string.ModerateRain'),
            "weaImg": "yu",
            "tem": "29",
            "win": $r('app.string.WestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "19",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "28",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "20",
            "wea": $r('app.string.ModerateRain'),
            "weaImg": "yu",
            "tem": "28",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "21",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "27",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "22",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "27",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "23",
            "wea": $r('app.string.ModerateRain'),
            "weaImg": "yu",
            "tem": "27",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "00",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "01",
            "wea": $r('app.string.ModerateRain'),
            "weaImg": "yu",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "02",
            "wea": $r('app.string.ModerateRain'),
            "weaImg": "yu",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "03",
            "wea": $r('app.string.ModerateRain'),
            "weaImg": "yu",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "04",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "05",
            "wea": $r('app.string.ModerateRain'),
            "weaImg": "yu",
            "tem": "25",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "06",
            "wea": $r('app.string.Rainy'),
            "weaImg": "yu",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "07",
            "wea": $r('app.string.ModerateRain'),
            "weaImg": "yu",
            "tem": "27",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          }
        ],
        "index": [
          {
            "title": $r('app.string.Humidity'),
            "level": $r('app.string.55Per'),
            "desc": $r('app.string.Humidity_desc2')
          },
          {
            "title": $r('app.string.Humidity_desc1'),
            "level": $r('app.string.tem35'),
            "desc": ""
          },
          {
            "title": $r('app.string.WindForce'),
            "level": $r('app.string.Breeze'),
            "desc": $r('app.string.WindForce_desc1')
          },
          {
            "title": $r('app.string.WindDirection'),
            "level": $r('app.string.SouthWind'),
            "desc": ""
          },
          {
            "title": $r('app.string.Clothing'),
            "level": $r('app.string.TShirt'),
            "desc": $r('app.string.Clothing_desc1')
          },
          {
            "title": $r('app.string.Sport'),
            "level": $r('app.string.SportRecommended'),
            "desc": ""
          },
          {
            "title": $r('app.string.Cold'),
            "level": $r('app.string.ColdEasy'),
            "desc": $r('app.string.ColdDesc')
          },
          {
            "title": $r('app.string.UV'),
            "level": $r('app.string.Weak'),
            "desc": $r('app.string.UVDesc2')
          }
        ]
      },
      {
        "day": $r('app.string.25th'),
        "date": "2022-06-25",
        "week": $r('app.string.Saturday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "yin",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "yin",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "yin",
        "tem": "34",
        "tem1": "36",
        "tem2": "22",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthWind'),
          $r('app.string.WinDesc')
        ],
        "winSpeed": "4-5 -> <3",
        "winMeter": "",
        "sunrise": "04:58",
        "sunset": "19:04",
        "air": "34",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.26th'),
        "date": "2022-06-26",
        "week": $r('app.string.Sunday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "yin",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "yin",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "yin",
        "tem": "36",
        "tem1": "38",
        "tem2": "27",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthWind'),
          $r('app.string.SouthWind')
        ],
        "winSpeed": "4-5",
        "winMeter": "",
        "sunrise": "04:59",
        "sunset": "19:04",
        "air": "29",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.27th'),
        "date": "2022-06-27",
        "week": $r('app.string.Monday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "cloudy",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "cloudy",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "cloudy",
        "tem": "36",
        "tem1": "36",
        "tem2": "26",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthWind'),
          $r('app.string.SouthWind')
        ],
        "winSpeed": "4-5",
        "winMeter": "",
        "sunrise": "04:59",
        "sunset": "19:04",
        "air": "26",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.28th'),
        "date": "2022-06-28",
        "week": $r('app.string.Tuesday'),
        "wea": $r('app.string.Sunny'),
        "weaImg": "sunny",
        "weaDay": $r('app.string.Sunny'),
        "weaDayImg": "sunny",
        "weaNight": $r('app.string.Sunny'),
        "weaNightImg": "sunny",
        "tem": "36",
        "tem1": "36",
        "tem2": "27",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthwestWind'),
          $r('app.string.SouthWind')
        ],
        "winSpeed": "4-5 -> 3-4",
        "winMeter": "",
        "sunrise": "04:59",
        "sunset": "19:04",
        "air": "38",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.29th'),
        "date": "2022-06-29",
        "week": $r('app.string.Wednesday'),
        "wea": $r('app.string.Sunny'),
        "weaImg": "sunny",
        "weaDay": $r('app.string.Sunny'),
        "weaDayImg": "sunny",
        "weaNight": $r('app.string.Sunny'),
        "weaNightImg": "sunny",
        "tem": "35",
        "tem1": "35",
        "tem2": "26",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.WinDesc'),
          $r('app.string.WinDesc')
        ],
        "winSpeed": "<3",
        "winMeter": "",
        "sunrise": "05:00",
        "sunset": "19:04",
        "air": "31",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      }
    ],
    "aqi": {
      "updateTime": "13:44",
      "cityId": "101210104",
      "city": $r('app.string.Tianjin'),
      "cityEn": "tianjin",
      "country": $r('app.string.China'),
      "countryEn": "China",
      "air": "50",
      "airLevel": $r('app.string.Excellent'),
      "airTips": $r('app.string.airTips8'),
      "pm25": "95",
      "pm25Desc": $r('app.string.Excellent'),
      "pm10": "180",
      "pm10Desc": $r('app.string.Excellent'),
      "o3": "30",
      "o3Desc": $r('app.string.Excellent'),
      "no2": "150",
      "no2Desc": $r('app.string.Excellent'),
      "so2": "65",
      "so2Desc": $r('app.string.Excellent'),
      "co": "19",
      "coDesc": "-",
      "kouzhao": $r('app.string.MaskNeed1'),
      "yundong": $r('app.string.exercise1'),
      "waichu": $r('app.string.goingOut1'),
      "kaichuang": $r('app.string.windows1'),
      "jinghuaqi": $r('app.string.purifier1')
    }
  },
  {
    "cityId": "101210105",
    "city":$r('app.string.Wuhan'),
    "cityEn": "wuhan",
    "country": $r('app.string.China'),
    "countryEn": "China",
    "updateTime": "2022-06-23 13:09:59",
    "data": [
      {
        "day": $r('app.string.23rd'),
        "date": "2022-06-23",
        "week": $r('app.string.Thursday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "yun",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "yun",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "yin",
        "tem": "35",
        "tem1": "39",
        "tem2": "25",
        "humidity": "40%",
        "visibility": "24km",
        "pressure": "998",
        "win": [
          $r('app.string.SouthwestWind'),
          $r('app.string.SouthwestWind')
        ],
        "winSpeed": '5-6 -> 3-4',
        "winMeter": "18km/h",
        "sunrise": "04:58",
        "sunset": "19:04",
        "air": "20",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [
          {
            "hours": "08",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "29",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3"
          },
          {
            "hours": "09",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "31",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "4"
          },
          {
            "hours": "10",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "32",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "5"
          },
          {
            "hours": "11",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yun",
            "tem": "34",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "5"
          },
          {
            "hours": "12",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yun",
            "tem": "34",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "5"
          },
          {
            "hours": "13",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yun",
            "tem": "35",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "6"
          },
          {
            "hours": "14",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yun",
            "tem": "36",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "5"
          },
          {
            "hours": "15",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yun",
            "tem": "35",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "6"
          },
          {
            "hours": "16",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yun",
            "tem": "35",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "5"
          },
          {
            "hours": "17",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yun",
            "tem": "35",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "4"
          },
          {
            "hours": "18",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yun",
            "tem": "34",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "4"
          },
          {
            "hours": "19",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yun",
            "tem": "32",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "4"
          },
          {
            "hours": "20",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yun",
            "tem": "31",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "4"
          },
          {
            "hours": "21",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "31",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "4"
          },
          {
            "hours": "22",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "30",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "4"
          },
          {
            "hours": "23",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "29",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3"
          },
          {
            "hours": "00",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "29",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3"
          },
          {
            "hours": "01",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "29",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3"
          },
          {
            "hours": "02",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "28",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3"
          },
          {
            "hours": "03",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "28",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3"
          },
          {
            "hours": "04",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "28",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3"
          },
          {
            "hours": "05",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "28",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3"
          },
          {
            "hours": "06",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "28",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3"
          },
          {
            "hours": "07",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "29",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3"
          }
        ],
        "index": [
          {
            "title": $r('app.string.Humidity'),
            "level": $r('app.string.45Per'),
            "desc": $r('app.string.Humidity_desc1')
          },
          {
            "title": $r('app.string.Humidity_desc1'),
            "level": $r('app.string.tem20'),
            "desc": ""
          },
          {
            "title": $r('app.string.WindForce'),
            "level": $r('app.string.Breeze'),
            "desc": $r('app.string.WindForce_desc1')
          },
          {
            "title": $r('app.string.WindDirection'),
            "level": $r('app.string.SouthWind'),
            "desc": ""
          },
          {
            "title": $r('app.string.Clothing'),
            "level": $r('app.string.TShirt'),
            "desc": $r('app.string.Clothing_desc1')
          },
          {
            "title": $r('app.string.Sport'),
            "level": $r('app.string.SportRecommended'),
            "desc": ""
          },
          {
            "title": $r('app.string.Cold'),
            "level": $r('app.string.ColdEasy'),
            "desc": $r('app.string.ColdDesc')
          },
          {
            "title": $r('app.string.UV'),
            "level": $r('app.string.Weak'),
            "desc": $r('app.string.UVDesc2')
          }
        ]
      },
      {
        "day": $r('app.string.Excellent'),
        "date": "2022-06-24",
        "week": $r('app.string.Friday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "cloudy",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "cloudy",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "cloudy",
        "tem": "27",
        "tem1": "29",
        "tem2": "22",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthwestWind'),
          $r('app.string.SouthwestWind')
        ],
        "winSpeed": '3-4',
        "winMeter": "",
        "sunrise": "04:58",
        "sunset": "19:04",
        "air": "25",
        "airLevel": $r('app.string.Excellent'),
        "airTips": $r('app.string.airTips9'),
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [
          {
            "hours": "08",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "yin",
            "tem": "25",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "09",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "27",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "10",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "27",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "11",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "28",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "12",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "28",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "13",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "28",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "14",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "27",
            "win": $r('app.string.WestWind'),
            "winSpeed": "4-5"
          },
          {
            "hours": "15",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "27",
            "win": $r('app.string.WestWind'),
            "winSpeed": "4-5"
          },
          {
            "hours": "16",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "26",
            "win": $r('app.string.WestWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "17",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "27",
            "win": $r('app.string.NorthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "18",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "27",
            "win": $r('app.string.WestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "19",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "26",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "20",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "25",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "21",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "25",
            "win": $r('app.string.SouthwestWind'),
            "winSpeed": "<3"
          },
          {
            "hours": "22",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "24",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "23",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "24",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "00",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "24",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "01",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "24",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "02",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "24",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "03",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "23",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "04",
            "wea": $r('app.string.Cloudy'),
            "weaImg": "cloudy",
            "tem": "24",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "05",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "25",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "06",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "25",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          },
          {
            "hours": "07",
            "wea": $r('app.string.Sunny'),
            "weaImg": "sunny",
            "tem": "26",
            "win": $r('app.string.SouthWind'),
            "winSpeed": "3-4"
          }
        ],
        "index": [
          {
            "title": $r('app.string.Humidity'),
            "level": $r('app.string.42Per'),
            "desc": $r('app.string.Humidity_desc1')
          },
          {
            "title": $r('app.string.Humidity_desc1'),
            "level": $r('app.string.tem25'),
            "desc": ""
          },
          {
            "title": $r('app.string.WindForce'),
            "level": $r('app.string.Breeze'),
            "desc": $r('app.string.WindForce_desc1')
          },
          {
            "title": $r('app.string.WindDirection'),
            "level": $r('app.string.SouthwestWind'),
            "desc": ""
          },
          {
            "title": $r('app.string.Clothing'),
            "level": $r('app.string.TShirt'),
            "desc": $r('app.string.Clothing_desc1')
          },
          {
            "title": $r('app.string.Sport'),
            "level": $r('app.string.SportRecommended1'),
            "desc": ""
          },
          {
            "title": $r('app.string.Cold'),
            "level": $r('app.string.ColdEasy'),
            "desc": $r('app.string.ColdDesc')
          },
          {
            "title": $r('app.string.UV'),
            "level": $r('app.string.Weak'),
            "desc": $r('app.string.UVDesc2')
          }
        ]
      },
      {
        "day": $r('app.string.25th'),
        "date": "2022-06-25",
        "week": $r('app.string.Saturday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "yun",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "yun",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "yun",
        "tem": "29",
        "tem1": "30",
        "tem2": "26",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthWind'),
          $r('app.string.WinDesc')
        ],
        "winSpeed": "4-5 -> <3",
        "winMeter": "",
        "sunrise": "04:58",
        "sunset": "19:04",
        "air": "34",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.26th'),
        "date": "2022-06-26",
        "week": $r('app.string.Sunday'),
        "wea": $r('app.string.Sunny'),
        "weaImg": "sunny",
        "weaDay": $r('app.string.Sunny'),
        "weaDayImg": "sunny",
        "weaNight": $r('app.string.Sunny'),
        "weaNightImg": "sunny",
        "tem": "36",
        "tem1": "40",
        "tem2": "30",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthWind'),
          $r('app.string.SouthWind')
        ],
        "winSpeed": "4-5",
        "winMeter": "",
        "sunrise": "04:59",
        "sunset": "19:04",
        "air": "29",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.27th'),
        "date": "2022-06-27",
        "week": $r('app.string.Monday'),
        "wea": $r('app.string.Sunny'),
        "weaImg": "sunny",
        "weaDay": $r('app.string.Sunny'),
        "weaDayImg": "sunny",
        "weaNight": $r('app.string.Sunny'),
        "weaNightImg": "sunny",
        "tem": "33",
        "tem1": "39",
        "tem2": "28",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthWind'),
          $r('app.string.SouthWind')
        ],
        "winSpeed": "4-5",
        "winMeter": "",
        "sunrise": "04:59",
        "sunset": "19:04",
        "air": "26",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.28th'),
        "date": "2022-06-28",
        "week": $r('app.string.Tuesday'),
        "wea": $r('app.string.Cloudy'),
        "weaImg": "cloudy",
        "weaDay": $r('app.string.Cloudy'),
        "weaDayImg": "cloudy",
        "weaNight": $r('app.string.Cloudy'),
        "weaNightImg": "cloudy",
        "tem": "35",
        "tem1": "38",
        "tem2": "28",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.SouthwestWind'),
          $r('app.string.SouthWind')
        ],
        "winSpeed": "4-5 -> 3-4",
        "winMeter": "",
        "sunrise": "04:59",
        "sunset": "19:04",
        "air": "38",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      },
      {
        "day": $r('app.string.29th'),
        "date": "2022-06-29",
        "week": $r('app.string.Wednesday'),
        "wea": $r('app.string.Sunny'),
        "weaImg": "sunny",
        "weaDay": $r('app.string.Sunny'),
        "weaDayImg": "sunny",
        "weaNight": $r('app.string.Sunny'),
        "weaNightImg": "sunny",
        "tem": "35",
        "tem1": "39",
        "tem2": "26",
        "humidity": "",
        "visibility": "",
        "pressure": "",
        "win": [
          $r('app.string.WinDesc'),
          $r('app.string.WinDesc')
        ],
        "winSpeed": "<3",
        "winMeter": "",
        "sunrise": "05:00",
        "sunset": "19:04",
        "air": "31",
        "airLevel": $r('app.string.Excellent'),
        "airTips": "",
        "alarm": {
          "alarmType": "",
          "alarmLevel": "",
          "alarmContent": ""
        },
        "hours": [],
        "index": []
      }
    ],
    "aqi": {
      "updateTime": "13:44",
      "cityId": "101210105",
      "city": $r('app.string.Wuhan'),
      "cityEn": "wuhan",
      "country": $r('app.string.China'),
      "countryEn": "China",
      "air": "29",
      "airLevel": $r('app.string.Excellent'),
      "airTips": $r('app.string.airTips2'),
      "pm25": "93",
      "pm25Desc": $r('app.string.Excellent'),
      "pm10": "178",
      "pm10Desc": $r('app.string.Excellent'),
      "o3": "17",
      "o3Desc": $r('app.string.Excellent'),
      "no2": "100",
      "no2Desc": $r('app.string.Excellent'),
      "so2": "66",
      "so2Desc": $r('app.string.Excellent'),
      "co": "18",
      "coDesc": "-",
      "kouzhao": $r('app.string.MaskNeed1'),
      "yundong": $r('app.string.exercise1'),
      "waichu": $r('app.string.goingOut1'),
      "kaichuang": $r('app.string.windows1'),
      "jinghuaqi": $r('app.string.purifier1')
    }
  }
];

export class CityFull {
  cityId: string = '';
  city: ResourceStr = '';
  cityEn: string = '';
  country: ResourceStr = '';
  countryEn: string = '';
  updateTime: string = '';
  data: WeatherItem[] = [];
  aqi: Aqi = new Aqi();
}

export class WeatherItem {
  day: ResourceStr = '';
  date: string = '';
  week: ResourceStr = '';
  wea: ResourceStr = '';
  weaImg: string = '';
  weaDay: ResourceStr = '';
  weaDayImg: string = '';
  weaNight: ResourceStr = '';
  weaNightImg: string = '';
  tem: string = '';
  tem1: string = '';
  tem2: string = '';
  humidity: string = '';
  visibility: string = '';
  pressure: string = '';
  win: ResourceStr[] = [];
  winSpeed: string = '';
  winMeter: string = '';
  sunrise: string = '';
  sunset: string = '';
  air: string = '';
  airLevel: ResourceStr = '';
  airTips: ResourceStr = '';
  alarm: AlarmItem = new AlarmItem();
  hours: HoursItem[] = [];
  index: IndexItem[] = [];
}

export class AlarmItem {
  alarmType: string = '';
  alarmLevel: string = '';
  alarmContent: string = '';
}

export class HoursItem {
  hours: string = '';
  wea: ResourceStr = '';
  weaImg: string = '';
  tem: string = '';
  win: ResourceStr = '';
  winSpeed: string = '';
}

export class IndexItem {
  title: ResourceStr = '';
  level: ResourceStr = '';
  desc: ResourceStr = '';
}

export class Aqi {
  updateTime: string = '';
  cityId: string = '';
  city: ResourceStr = '';
  cityEn: string = '';
  country: ResourceStr = '';
  countryEn: string = '';
  air: string = '';
  airLevel: ResourceStr = '';
  airTips: ResourceStr = '';
  pm25: string = '';
  pm25Desc: ResourceStr = '';
  pm10: string = '';
  pm10Desc: ResourceStr = '';
  o3: string = '';
  o3Desc: ResourceStr = '';
  no2: string = '';
  no2Desc: ResourceStr = '';
  so2: string = '';
  so2Desc: ResourceStr = '';
  co: string = '';
  coDesc: string = '';
  kouzhao: ResourceStr = '';
  yundong: ResourceStr = '';
  waichu: ResourceStr = '';
  kaichuang: ResourceStr = '';
  jinghuaqi: ResourceStr = '';
}