# Copyright (c) 2022-2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

build ets-plugin:
    stage: build
    interruptible: true
    extends: .linux-vm-shell-task
    before_script:
        - !reference [.setup, script]
        - cd arkoala/ets-plugin
    script:
        - npm run compile
    needs:
        - install node modules (arkoala)
        - install node modules (incremental)
        - build compat
        - build common
    artifacts:
        expire_in: 2 days
        paths:
            - arkoala/ets-plugin/build/lib

test ets-plugin (arkoala):
    stage: test
    interruptible: true
    extends: .linux-vm-shell-task
    before_script:
        - !reference [.setup, script]
        - cd arkoala/ets-plugin
    script:
        - npm run test:arkoala:ets
    needs:
        - install node modules (arkoala)
        - install node modules (incremental)
        - build compat
        - build common
        - build ets-plugin
        - build harness

test ets-plugin (arkts):
    stage: test
    interruptible: true
    extends: .linux-vm-shell-task
    before_script:
        - !reference [.setup, script]
        - cd arkoala/ets-plugin
    script:
        - npm run test:arkts:ets
    needs:
        - install node modules (arkoala)
        - install node modules (incremental)
        - build compat
        - build common
        - build ets-plugin
        - build harness

test ets-plugin (koala):
    stage: test
    interruptible: true
    extends: .linux-vm-shell-task
    before_script:
        - !reference [.setup, script]
        - cd arkoala/ets-plugin
    script:
        - npm run test:koala:ets
    needs:
        - install node modules (arkoala)
        - install node modules (incremental)
        - build compat
        - build common
        - build ets-plugin
        - build harness

test ets-plugin (arkoala spec):
    stage: test
    interruptible: true
    extends: .linux-vm-shell-task
    before_script:
        - !reference [.setup, script]
        - cd arkoala/ets-plugin
    script:
        - npm run sync:spec
        - npm run test:arkoala:spec
    needs:
        - install node modules (arkoala)
        - install node modules (incremental)
        - build compat
        - build common
        - build ets-plugin
        - build harness

test ets-plugin (arkts spec):
    stage: test
    interruptible: true
    extends: .linux-vm-shell-task
    before_script:
        - !reference [.setup, script]
        - cd arkoala/ets-plugin
    script:
        - npm run sync:spec
        - npm run test:arkts:spec
    needs:
        - install node modules (arkoala)
        - install node modules (incremental)
        - build compat
        - build common
        - build ets-plugin
        - build harness

test ets-plugin (koala spec):
    stage: test
    interruptible: true
    extends: .linux-vm-shell-task
    before_script:
        - !reference [.setup, script]
        - cd arkoala/ets-plugin
    script:
        - npm run sync:spec
        - npm run test:koala:spec
    needs:
        - install node modules (arkoala)
        - install node modules (incremental)
        - build compat
        - build common
        - build ets-plugin
        - build harness

pack ets-plugin:
  extends:
    - .npm-pack
    - .linux-vm-shell-task
  variables:
    PACKAGE_DIR: arkoala/ets-plugin
  needs:
    - build ets-plugin

publish ets-plugin:
  extends: 
    - .npm-publish
    - .linux-vm-shell-task
  variables:
    PACKAGE_DIR: arkoala/ets-plugin
  dependencies:
    - build ets-plugin