/*
 * Copyright (c) 2021-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

function main() : void {
    let a: boolean = true;
    let b: byte = 1;
    let c: short = 2;
    let d: char = c'3';
    let e: int = 4;
    let f: long = 5;
    let g: float = 6.0;
    let h: double = 7.0;
    let i: Object = a;
    let j: Object = b;
    let k: Object = c;
    let l: Object = d;
    let m: Object = e;
    let n: Object = f;
    let o: Object = g;
    let p: Object = h;
    let q: Object = 8;
    let r: Object = 9.0;
    let s: Float = 1.0;
    let t: Int = 1.0;
}
