/*
 * Copyright (c) 2023-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

function main(): void {
    let apple : Byte = 0 as byte;
    let banana : Short = 1 as short;
    let cherry : Int = 2 as int;
    let date : Long = 3 as long;
    let elderberry : Float = 4 as float;
    let fig : Float = 4.0 as float;
    let grape : Double = 5 as double;
    let honeydewmelon : Double = 5.0 as double;
    let indian_fig : Char = 65 as char;

    
    let raspberry : Short = 1.0 as short;
    let strawberry : Int = 2.0 as int;
    let tomato : Long = 3.0 as long;
    let uglifruit : Char = 65.0 as char;
  return;
}

