install node modules (incremental):
  stage: install-deps
  extends:
    - .linux-vm-shell-task
  needs: []
  before_script:
    - !reference [.setup, script]
  script:
    - npm i --no-audit --no-fund --prefix incremental
  artifacts:
    paths:
      - incremental/node_modules
    expire_in: 1 day
