/*
 * Copyright (c) 2024-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

final /* @@ label */kngkgj class /* @@ label1 */B /* @@ label2 */{

}

/* @@@ label Error SyntaxError: Unexpected token 'kngkgj'. */
/* @@? 16:21 Error TypeError: Cannot find type 'kngkgj'. */
/* @@? 16:21 Error TypeError: Class literal is not yet supported. */
/* @@@ label1 Error SyntaxError: Unexpected token 'B'. */
/* @@? 16:49 Error TypeError: Unresolved reference B */
/* @@@ label2 Error SyntaxError: Unexpected token '{'. */
