/*
 * Copyright (c) 2024-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

let arr: Int[] | null = [1, 4, 5] as Int[];
let test = arr?.[1] ?? "unknown";

let arr2: String[] | null;
let test2 = arr2?.[100] ?? "unknown2";

/* @@? 20:13 Warning Warning: Variable 'arr2' is used before being assigned.  */
