/*
 * Copyright (c) 2024-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

interface inter {
	get value(): string;
	set value(value: string);
}

class A {}

class B extends A implements inter {
	value: string = "1";
}

function foo(a: Partial<A>): void {}


function foa(b: B): void {
	/* @@ label */foo(/* @@ label1 */b);
}

/* @@@ label1 Error TypeError: Type 'B' is not compatible with type 'Partial<A>' at index 1 */
/* @@@ label Error TypeError: No matching call signature for foo(B) */
