/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use Logger file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommonConstant {
  static readonly WebConstant_BORDER_WIDTH: number = 1;
  static readonly WebConstant_FULL_WIDTH: string = '100%';
  static readonly WebConstant_BUTTON_SMALL_WIDTH: number = 72;
  static readonly WebConstant_FIVE_HUNDRED: number = 500;

  static readonly WebConstant_FULL_HEIGHT: string = '100%';
  static readonly WebConstant_BUTTON_HEIGHT: number = 28;


  static readonly WebConstant_TEN_PERCENT: string = '10%';
  static readonly WebConstant_TWELVE_PERCENT: string = '12%';
  static readonly WebConstant_FIFTEEN_PERCENT: string = '15%';
  static readonly WebConstant_THIRTY_PERCENT: string = '30%';
  static readonly WebConstant_FORTY_PERCENT: string = '40%';
  static readonly WebConstant_FIFTY_PERCENT: string = '50%';
  static readonly WebConstant_SIXTY_PERCENT: string = '60%';
  static readonly WebConstant_SEVENTY_PERCENT: string = '70%';
  static readonly WebConstant_EIGHTY_PERCENT: string = '80%';
  static readonly WebConstant_NINETY_PERCENT: string = '90%';
}