// This file has been autogenerated. Do not update manually.
import { MyComponent as Entry0 } from "./@builder"
import { CustomContainerUser as Entry1 } from "./@builderParam"
import { Index as Entry2 } from "./@builderWithComponent"
import { Index as Entry3 } from "./@builderWithForEach"
import { TestPage as Entry4 } from "./@builderWithLinkData"
import { CompA as Entry5 } from "./@consume_@provide"
import { CustomDialogUser as Entry6 } from "./@customDialog"
import { ParentComponent as Entry7 } from "./@link"
import { Parent as Entry8 } from "./@objectLink"
import { ViewB as Entry9 } from "./@observed_@objectLink"
import { HomePreviewComponent as Entry10 } from "./@preview"
import { CustomY as Entry11 } from "./@prop"
import { Index as Entry12 } from "./@propComplexType"
import { StatePage as Entry13 } from "./@state"
import { MyComponent as Entry14 } from "./@storageLink"
import { MyComponent as Entry15 } from "./@storageProp"
import { FancyUse as Entry16 } from "./@styles"
import { FancyUseExp as Entry17 } from "./@stylesExport"
import { CompA as Entry18 } from "./@watch"
import { ParentView as Entry19 } from "./GridItem"
import { ParentView as Entry20 } from "./ListItem"
import { HomeComponent as Entry21 } from "./XComponentContainer"
import { HomeComponent as Entry22 } from "./animatableExtend"
import { TransitionExample as Entry23 } from "./animateTo"
import { MyComponent as Entry24 } from "./appStorage"
import { ButtonExample as Entry25 } from "./button"
import { Index as Entry26 } from "./component_object"
import { MyComponent as Entry27 } from "./custom_component"
import { Index as Entry28 } from "./decoratorKeyCheck"
import { MyComponent as Entry29 } from "./forEachSecondFunction"
import { Index as Entry30 } from "./forEachTwo"
import { ParentView as Entry31 } from "./foreach"
import { Index as Entry32 } from "./handleCustomBuilder"
import { MyComponent as Entry33 } from "./id_if"
import { IFView as Entry34 } from "./if"
import { CustomDialogUser as Entry35 } from "./import@CustomDialog"
import { ViewB as Entry36 } from "./import@Observed"
import { ImportTest as Entry37 } from "./importAllEts"
import { ImportTest as Entry38 } from "./importEts"
import { ImportTest as Entry39 } from "./importExportEts"
import { ImportTest as Entry40 } from "./importExportNest"
import { ImportTest as Entry41 } from "./importTs"
import { Test as Entry42 } from "./lazyforeach"
import { LocalStorageComponent as Entry43 } from "./localStorage"
import { LocalStorageComponent as Entry44 } from "./localStorageForBoth"
import { LocalStorageComponent as Entry45 } from "./localStorageForRoute"
import { LocalStorageComponent as Entry46 } from "./localStorageForStorage"
import { LongPressGestureExample as Entry47 } from "./longPressGesture"
import { PageTransitionExample1 as Entry48 } from "./pageTransition"
import { PanGestureExample as Entry49 } from "./panGestrue"
import { PinchGestureExample as Entry50 } from "./pinchGesture"
import { HomeComponent as Entry51 } from "./recycle"
import { HomeComponent as Entry52 } from "./recycle_function_array"
import { HomeComponent as Entry53 } from "./recycle_reuseId"
import { RotationGestureExample as Entry54 } from "./rotationGesture"
import { SwipeGestureExample as Entry55 } from "./swipeGesture"
import { TabSimple as Entry56 } from "./tab"
import { TapGestureExample as Entry57 } from "./tapGesture"

export function registerRoutes() {
	const __forceEntry0Use = Entry0
	const __forceEntry1Use = Entry1
	const __forceEntry2Use = Entry2
	const __forceEntry3Use = Entry3
	const __forceEntry4Use = Entry4
	const __forceEntry5Use = Entry5
	const __forceEntry6Use = Entry6
	const __forceEntry7Use = Entry7
	const __forceEntry8Use = Entry8
	const __forceEntry9Use = Entry9
	const __forceEntry10Use = Entry10
	const __forceEntry11Use = Entry11
	const __forceEntry12Use = Entry12
	const __forceEntry13Use = Entry13
	const __forceEntry14Use = Entry14
	const __forceEntry15Use = Entry15
	const __forceEntry16Use = Entry16
	const __forceEntry17Use = Entry17
	const __forceEntry18Use = Entry18
	const __forceEntry19Use = Entry19
	const __forceEntry20Use = Entry20
	const __forceEntry21Use = Entry21
	const __forceEntry22Use = Entry22
	const __forceEntry23Use = Entry23
	const __forceEntry24Use = Entry24
	const __forceEntry25Use = Entry25
	const __forceEntry26Use = Entry26
	const __forceEntry27Use = Entry27
	const __forceEntry28Use = Entry28
	const __forceEntry29Use = Entry29
	const __forceEntry30Use = Entry30
	const __forceEntry31Use = Entry31
	const __forceEntry32Use = Entry32
	const __forceEntry33Use = Entry33
	const __forceEntry34Use = Entry34
	const __forceEntry35Use = Entry35
	const __forceEntry36Use = Entry36
	const __forceEntry37Use = Entry37
	const __forceEntry38Use = Entry38
	const __forceEntry39Use = Entry39
	const __forceEntry40Use = Entry40
	const __forceEntry41Use = Entry41
	const __forceEntry42Use = Entry42
	const __forceEntry43Use = Entry43
	const __forceEntry44Use = Entry44
	const __forceEntry45Use = Entry45
	const __forceEntry46Use = Entry46
	const __forceEntry47Use = Entry47
	const __forceEntry48Use = Entry48
	const __forceEntry49Use = Entry49
	const __forceEntry50Use = Entry50
	const __forceEntry51Use = Entry51
	const __forceEntry52Use = Entry52
	const __forceEntry53Use = Entry53
	const __forceEntry54Use = Entry54
	const __forceEntry55Use = Entry55
	const __forceEntry56Use = Entry56
	const __forceEntry57Use = Entry57
}
