/*
 * Copyright (c) 2022-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const JSValue: string = 'ESObject';
export const KitPrefix: string[] = [];
export const BuiltInType: string[] = ['Symbol'];
export const ETSKeyword: string[] = ['Class', 'ESObject', 'MethodType'];
export const UtilityTypes = [
    'Capitalize',
    'ConstructorParameters',
    'Exclude',
    'Extract',
    'InstanceType',
    'Lowercase',
    'NonNullable',
    'NoInfer',
    'Omit',
    'OmitThisParameter',
    'Parameters',
    'Pick',
    'ReturnType',
    'ThisParameterType',
    'ThisType',
    'Uncapitalize',
    'Uppercase'
];
export const SpecificTypes = [
    'AnyKeyword',
    'ConditionalType',
    'ConstructorType',
    'FunctionType',
    'IndexedAccessType',
    'IndexSignature',
    'IntersectionType',
    'MappedType',
    'ObjectLiteralExpression',
    'SymbolKeyword',
    'TemplateLiteralType',
    'UnknownKeyword'
];
export const FINAL_CLASS: string[] = [
    'ArgumentOutOfRangeException',
    'ArrayIndexOutOfBoundsError',
    'ArrayStoreError',
    'ArrayType',
    'ArrayValue',
    'ArithmeticError',
    'AtomicFlag',
    'Boolean',
    'BooleanType',
    'BooleanValue',
    'Byte',
    'ByteType',
    'ByteValue',
    'CallBodyDefault',
    'CallBodyFunction',
    'CallBodyMethod',
    'CallBodyErasedFunction',
    'Char',
    'CharType',
    'CharValue',
    'Class',
    'ClassCastError',
    'ClassType',
    'ClassValue',
    'Chrono',
    'Console',
    'Coroutine',
    'CoroutineExtras',
    'DebuggerAPI',
    'Double',
    'DoubleType',
    'DoubleValue',
    'EnumConstant',
    'EnumType',
    'Field',
    'FieldCreator',
    'FinalizableWeakRef',
    'FinalizationRegistry',
    'Float',
    'FloatType',
    'FloatValue',
    'GC',
    'IllegalArgumentException',
    'InterfaceType',
    'Int',
    'IntIntValue',
    'IntType',
    'JSError',
    'JSRuntime',
    'JSValue',
    'LambdaType',
    'LambdaValue',
    'Logger',
    'Long',
    'LongType',
    'LongValue',
    'Method',
    'MethodCreator',
    'MethodType',
    'NegativeArraySizeError',
    'NoDataException',
    'NullType',
    'NullValue',
    'Parameter',
    'ParameterCreator',
    'Promise',
    'Runtime',
    'RuntimeException',
    'Short',
    'ShortType',
    'ShortValue',
    'String',
    'StringBuilder',
    'StringIndexOutOfBoundsError',
    'StringType',
    'StringValue',
    'TupleType',
    'Types',
    'UnionCase',
    'UnionType',
    'UnsupportedOperationException',
    'UndefinedType',
    'UndefinedValue',
    'Void',
    'VoidType',
    'VoidValue',
    'WeakRef'
];
