/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*---
desc: Unary plus operator
assert: The type of the operand expression with the unary operator ‘+’ must be convertible (see Implicit Conversions) to a numeric type (see Numeric Types). Otherwise, a compile-time error occurs.
tags: [negative, compile-only]
---*/

function main(): void {
  let c = "text"
  assertEQ(+c, "text")
}
