/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated file by gen_null_arg_tests.rb script -- DO NOT EDIT!

#include "libabckit/include/c/abckit.h"
#include "libabckit/include/c/metadata_core.h"
#include "libabckit/include/c/extensions/arkts/metadata_arkts.h"
#include "libabckit/include/c/extensions/js/metadata_js.h"
#include "libabckit/include/c/ir_core.h"
#include "libabckit/include/c/isa/isa_dynamic.h"
#include "libabckit/src/include_v2/c/isa/isa_static.h"

#include "helpers/helpers.h"
#include "helpers/helpers_nullptr.h"

#include <gtest/gtest.h>

namespace libabckit::test {

static auto g_isaApiDynamicImp = AbckitGetIsaApiDynamicImpl(ABCKIT_VERSION_RELEASE_1_0_0);

class LibAbcKitNullptrTestsIsaApiDynamicImpl0 : public ::testing::Test {};

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreateiterresultobj,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCreateiterresultobj)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCreateiterresultobj);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateResumegenerator,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateResumegenerator)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateResumegenerator);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStprivateproperty,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateStprivateproperty)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStprivateproperty);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallarg0,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCallarg0)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallarg0);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeWideldsendableexternalmodulevar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCallruntimeWideldsendableexternalmodulevar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeWideldsendableexternalmodulevar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeIstrue,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCallruntimeIstrue)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeIstrue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iGetOpcode,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iGetOpcode)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iGetOpcode);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iGetModule,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iGetModule)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iGetModule);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAsyncfunctionreject,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateAsyncfunctionreject)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateAsyncfunctionreject);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStthisbyname,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateStthisbyname)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStthisbyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSupercallthisrange,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateSupercallthisrange)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateSupercallthisrange);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStobjbyvalue,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateStobjbyvalue)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStobjbyvalue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateIsin,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateIsin)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateIsin);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateIf,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateIf)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateIf);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdobjbyindex,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateWideLdobjbyindex)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideLdobjbyindex);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdnan,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateLdnan)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdnan);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSupercallarrowrange,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateSupercallarrowrange)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateSupercallarrowrange);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateInc,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateInc)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateInc);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGreatereq,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateGreatereq)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateGreatereq);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbyname,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateStownbyname)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStownbyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTrystglobalbyname,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateTrystglobalbyname)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateTrystglobalbyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateMul2,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateMul2)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateMul2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStrictnoteq,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateStrictnoteq)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStrictnoteq);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNewobjrange,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateNewobjrange)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateNewobjrange);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefinegettersetterbyvalue,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateDefinegettersetterbyvalue)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateDefinegettersetterbyvalue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLoadString,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateLoadString)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLoadString);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNewlexenv,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateNewlexenv)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateNewlexenv);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLesseq,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateLesseq)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLesseq);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStmodulevar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateWideStmodulevar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideStmodulevar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSupercallspread,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateSupercallspread)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateSupercallspread);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdlexvar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateLdlexvar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdlexvar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeCreateprivateproperty,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCallruntimeCreateprivateproperty)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeCreateprivateproperty);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowUndefinedifhole,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateThrowUndefinedifhole)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateThrowUndefinedifhole);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNewlexenvwithname,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateNewlexenvwithname)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateNewlexenvwithname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCopyrestargs,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateWideCopyrestargs)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideCopyrestargs);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbyvalue,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateStownbyvalue)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStownbyvalue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdpatchvar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateWideLdpatchvar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideLdpatchvar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefinefieldbyname,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateDefinefieldbyname)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateDefinefieldbyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStricteq,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateStricteq)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStricteq);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdprivateproperty,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateLdprivateproperty)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdprivateproperty);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iGetExportDescriptor,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iGetExportDescriptor)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iGetExportDescriptor);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeDefinefieldbyindex,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCallruntimeDefinefieldbyindex)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeDefinefieldbyindex);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreateemptyarray,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCreateemptyarray)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCreateemptyarray);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLess,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateLess)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLess);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideNewlexenv,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateWideNewlexenv)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideNewlexenv);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdtrue,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateLdtrue)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdtrue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTonumeric,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateTonumeric)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateTonumeric);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetasynciterator,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateGetasynciterator)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateGetasynciterator);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowUndefinedifholewithname,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateThrowUndefinedifholewithname)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateThrowUndefinedifholewithname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCopyrestargs,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCopyrestargs)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCopyrestargs);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStobjbyindex,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateWideStobjbyindex)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideStobjbyindex);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetnextpropname,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateGetnextpropname)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateGetnextpropname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateApply,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateApply)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateApply);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdthisbyname,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateLdthisbyname)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdthisbyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateIsfalse,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateIsfalse)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateIsfalse);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeLdsendablevar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCallruntimeLdsendablevar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeLdsendablevar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSetgeneratorstate,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateSetgeneratorstate)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateSetgeneratorstate);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeWideldsendablevar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCallruntimeWideldsendablevar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeWideldsendablevar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdglobalvar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateLdglobalvar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdglobalvar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreateobjectwithbuffer,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCreateobjectwithbuffer)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCreateobjectwithbuffer);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNewobjapply,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateNewobjapply)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateNewobjapply);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStlexvar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateStlexvar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStlexvar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateInstanceof,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateInstanceof)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateInstanceof);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateReturn,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateReturn)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateReturn);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDynamicimport,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateDynamicimport)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateDynamicimport);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbynamewithnameset,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateStownbynamewithnameset)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStownbynamewithnameset);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTryldglobalbyname,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateTryldglobalbyname)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateTryldglobalbyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStownbyindex,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateWideStownbyindex)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideStownbyindex);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAnd2,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateAnd2)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateAnd2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateShl2,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateShl2)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateShl2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStlexvar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateWideStlexvar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideStlexvar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideNewlexenvwithname,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateWideNewlexenvwithname)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideNewlexenvwithname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAshr2,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateAshr2)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateAshr2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbyvaluewithnameset,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateStownbyvaluewithnameset)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStownbyvaluewithnameset);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallthis3,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCallthis3)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallthis3);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetresumemode,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateGetresumemode)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateGetresumemode);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStglobalvar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateStglobalvar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStglobalvar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeLdsendableexternalmodulevar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCallruntimeLdsendableexternalmodulevar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeLdsendableexternalmodulevar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStarrayspread,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateStarrayspread)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStarrayspread);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdfalse,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateLdfalse)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdfalse);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAsyncgeneratorresolve,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateAsyncgeneratorresolve)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateAsyncgeneratorresolve);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAdd2,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateAdd2)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateAdd2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdinfinity,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateLdinfinity)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdinfinity);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSub2,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateSub2)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateSub2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeWidenewsendableenv,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCallruntimeWidenewsendableenv)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeWidenewsendableenv);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdthis,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateLdthis)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdthis);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTestin,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateTestin)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateTestin);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreateobjectwithexcludedkeys,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCreateobjectwithexcludedkeys)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCreateobjectwithexcludedkeys);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDebugger,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateDebugger)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateDebugger);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowConstassignment,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateThrowConstassignment)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateThrowConstassignment);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCatchPhi,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCatchPhi)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCatchPhi);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreategeneratorobj,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCreategeneratorobj)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCreategeneratorobj);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdexternalmodulevar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateWideLdexternalmodulevar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideLdexternalmodulevar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSuspendgenerator,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateSuspendgenerator)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateSuspendgenerator);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNeg,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateNeg)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateNeg);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetunmappedargs,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateGetunmappedargs)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateGetunmappedargs);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeLdsendableclass,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCallruntimeLdsendableclass)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeLdsendableclass);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeIsfalse,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCallruntimeIsfalse)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeIsfalse);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallthis0,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateCallthis0)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallthis0);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCallrange,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateWideCallrange)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideCallrange);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdobjbyname,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl0, iCreateLdobjbyname)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdobjbyname);
}

}  // namespace libabckit::test
