/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated file by gen_null_arg_tests.rb script -- DO NOT EDIT!

#include "libabckit/include/c/abckit.h"
#include "libabckit/include/c/metadata_core.h"
#include "libabckit/include/c/extensions/arkts/metadata_arkts.h"
#include "libabckit/include/c/extensions/js/metadata_js.h"
#include "libabckit/include/c/ir_core.h"
#include "libabckit/include/c/isa/isa_dynamic.h"
#include "libabckit/src/include_v2/c/isa/isa_static.h"

#include "helpers/helpers.h"
#include "helpers/helpers_nullptr.h"

#include <gtest/gtest.h>

namespace libabckit::test {

static auto g_isaApiDynamicImp = AbckitGetIsaApiDynamicImpl(ABCKIT_VERSION_RELEASE_1_0_0);

class LibAbcKitNullptrTestsIsaApiDynamicImpl1 : public ::testing::Test {};

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdobjbyname,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateLdobjbyname)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdobjbyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDiv2,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateDiv2)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateDiv2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateEq,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateEq)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateEq);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefinepropertybyname,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateDefinepropertybyname)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateDefinepropertybyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdnull,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateLdnull)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdnull);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGettemplateobject,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateGettemplateobject)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateGettemplateobject);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateMod2,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateMod2)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateMod2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdfunction,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateLdfunction)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdfunction);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDec,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateDec)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateDec);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallthis1,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCallthis1)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallthis1);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateIstrue,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateIstrue)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateIstrue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdlocalmodulevar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateWideLdlocalmodulevar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideLdlocalmodulevar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeDefineprivateproperty,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCallruntimeDefineprivateproperty)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeDefineprivateproperty);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideGetmodulenamespace,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateWideGetmodulenamespace)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideGetmodulenamespace);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeDefinefieldbyvalue,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCallruntimeDefinefieldbyvalue)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeDefinefieldbyvalue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeCallinit,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCallruntimeCallinit)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeCallinit);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateOr2,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateOr2)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateOr2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGreater,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateGreater)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateGreater);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdsymbol,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateLdsymbol)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdsymbol);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreateasyncgeneratorobj,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCreateasyncgeneratorobj)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCreateasyncgeneratorobj);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdbigint,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateLdbigint)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdbigint);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetpropiterator,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateGetpropiterator)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateGetpropiterator);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateXor2,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateXor2)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateXor2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDelobjprop,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateDelobjprop)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateDelobjprop);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeNotifyconcurrentresult,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCallruntimeNotifyconcurrentresult)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeNotifyconcurrentresult);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetiterator,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateGetiterator)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateGetiterator);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefinemethod,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateDefinemethod)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateDefinemethod);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAsyncfunctionawaituncaught,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateAsyncfunctionawaituncaught)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateAsyncfunctionawaituncaught);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetmodulenamespace,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateGetmodulenamespace)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateGetmodulenamespace);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowNotexists,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateThrowNotexists)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateThrowNotexists);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreatePoplexenv,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreatePoplexenv)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreatePoplexenv);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreateemptyobject,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCreateemptyobject)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCreateemptyobject);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdundefined,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateLdundefined)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdundefined);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateReturnundefined,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateReturnundefined)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateReturnundefined);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStsuperbyvalue,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateStsuperbyvalue)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStsuperbyvalue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallthis2,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCallthis2)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallthis2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeDefinesendableclass,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCallruntimeDefinesendableclass)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeDefinesendableclass);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowDeletesuperproperty,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateThrowDeletesuperproperty)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateThrowDeletesuperproperty);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStthisbyvalue,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateStthisbyvalue)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStthisbyvalue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iSetModule,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iSetModule)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iSetModule);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCreateobjectwithexcludedkeys,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateWideCreateobjectwithexcludedkeys)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideCreateobjectwithexcludedkeys);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideSupercallthisrange,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateWideSupercallthisrange)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideSupercallthisrange);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStobjbyindex,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateStobjbyindex)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStobjbyindex);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeStsendablevar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCallruntimeStsendablevar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeStsendablevar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdobjbyindex,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateLdobjbyindex)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdobjbyindex);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdhole,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateLdhole)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdhole);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallthisrange,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCallthisrange)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallthisrange);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdsuperbyvalue,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateLdsuperbyvalue)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdsuperbyvalue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdlexvar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateWideLdlexvar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideLdlexvar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateShr2,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateShr2)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateShr2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeTopropertykey,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCallruntimeTopropertykey)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeTopropertykey);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iSetExportDescriptor,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iSetExportDescriptor)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iSetExportDescriptor);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreatearraywithbuffer,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCreatearraywithbuffer)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCreatearraywithbuffer);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStobjbyname,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateStobjbyname)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStobjbyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSetobjectwithproto,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateSetobjectwithproto)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateSetobjectwithproto);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideNewobjrange,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateWideNewobjrange)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideNewobjrange);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdthisbyvalue,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateLdthisbyvalue)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdthisbyvalue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNoteq,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateNoteq)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateNoteq);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStpatchvar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateWideStpatchvar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideStpatchvar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallargs2,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCallargs2)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallargs2);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowIfsupernotcorrectcall,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateThrowIfsupernotcorrectcall)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateThrowIfsupernotcorrectcall);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefineclasswithbuffer,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateDefineclasswithbuffer)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateDefineclasswithbuffer);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdlocalmodulevar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateLdlocalmodulevar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdlocalmodulevar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNot,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateNot)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateNot);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAsyncfunctionresolve,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateAsyncfunctionresolve)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateAsyncfunctionresolve);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStmodulevar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateStmodulevar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStmodulevar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowPatternnoncoercible,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateThrowPatternnoncoercible)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateThrowPatternnoncoercible);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdsuperbyname,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateLdsuperbyname)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdsuperbyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAsyncfunctionenter,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateAsyncfunctionenter)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateAsyncfunctionenter);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iSetConditionCode,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iSetConditionCode)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iSetConditionCode);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallargs3,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCallargs3)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallargs3);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeNewsendableenv,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCallruntimeNewsendableenv)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeNewsendableenv);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iGetConditionCode,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iGetConditionCode)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iGetConditionCode);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCallthisrange,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateWideCallthisrange)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideCallthisrange);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAsyncgeneratorreject,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateAsyncgeneratorreject)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateAsyncgeneratorreject);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdexternalmodulevar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateLdexternalmodulevar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdexternalmodulevar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideSupercallarrowrange,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateWideSupercallarrowrange)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateWideSupercallarrowrange);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iGetImportDescriptor,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iGetImportDescriptor)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iGetImportDescriptor);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallrange,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCallrange)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallrange);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStsuperbyname,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateStsuperbyname)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStsuperbyname);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeWidestsendablevar,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCallruntimeWidestsendablevar)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallruntimeWidestsendablevar);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbyindex,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateStownbyindex)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateStownbyindex);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTypeof,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateTypeof)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateTypeof);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iSetImportDescriptor,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iSetImportDescriptor)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iSetImportDescriptor);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowIfnotobject,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateThrowIfnotobject)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateThrowIfnotobject);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallarg1,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCallarg1)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCallarg1);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefinefunc,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateDefinefunc)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateDefinefunc);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdobjbyvalue,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateLdobjbyvalue)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdobjbyvalue);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrow,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateThrow)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateThrow);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateExp,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateExp)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateExp);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTonumber,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateTonumber)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateTonumber);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdglobal,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateLdglobal)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdglobal);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCopydataproperties,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateCopydataproperties)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateCopydataproperties);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdnewtarget,
// abc-kind=NoABC, category=negative-nullptr
TEST_F(LibAbcKitNullptrTestsIsaApiDynamicImpl1, iCreateLdnewtarget)
{
    helpers_nullptr::TestNullptr(g_isaApiDynamicImp->iCreateLdnewtarget);
}

}  // namespace libabckit::test
