build fast-arktsc:
  stage: build
  interruptible: true
  extends: .linux-vm-shell-task
  before_script:
    - !reference [.setup, script]
    - cd incremental/tools/fast-arktsc
  script:
    - npm run compile
  needs:
    - install node modules (incremental)
  artifacts:
    expire_in: 2 days
    paths:
      - incremental/tools/fast-arktsc/lib

pack fast-arktsc:
  extends:
    - .npm-pack
    - .linux-vm-shell-task
  variables:
    PACKAGE_DIR: incremental/tools/fast-arktsc
  needs:
    - build fast-arktsc

publish fast-arktsc:
  extends: 
    - .npm-publish
    - .linux-vm-shell-task
  variables:
    PACKAGE_DIR: incremental/tools/fast-arktsc
  dependencies:
    - build fast-arktsc