/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const INVALID_IDENTIFIER_KEYWORDS = [
  'abstract',
  'else',
  'internal',
  'static',
  'as',
  'enum',
  'launch',
  'switch',
  'async',
  'export',
  'let',
  'super',
  'await',
  'extends',
  'native',
  'this',
  'break',
  'false',
  'new',
  'throw',
  'case',
  'final',
  'null',
  'true',
  'class',
  'for',
  'override',
  'try',
  'const',
  'function',
  'package',
  'undefined',
  'constructor',
  'if',
  'private',
  'while',
  'continue',
  'implements',
  'protected',
  'default',
  'import',
  'public',
  'do',
  'interface',
  'return',
  'boolean',
  'double',
  'number',
  'Boolean',
  'Double',
  'Number',
  'byte',
  'float',
  'object',
  'Byte',
  'Float',
  'Object',
  'bigint',
  'int',
  'short',
  'Bigint',
  'Int',
  'Short',
  'char',
  'long',
  'string',
  'Char',
  'Long',
  'String',
  'void',
  'Awaited',
  'NoInfer',
  'Pick',
  'ConstructorParameters',
  'NonNullable',
  'ReturnType',
  'Exclude',
  'Omit',
  'ThisParameterType',
  'Extract',
  'OmitThisParameter',
  'ThisType',
  'InstanceType',
  'Parameters',
  'Capitalize',
  'Uncapitalize',
  'Lowercase',
  'Uppercase',
  'ArrayBufferTypes',
  'Function',
  'Proxy',
  'AsyncGenerator',
  'Generator',
  'ProxyHandler',
  'AsyncGeneratorFunction',
  'GeneratorFunction',
  'Symbol',
  'AsyncIterable',
  'IArguments',
  'TemplateStringsArray',
  'AsyncIterableIterator',
  'IteratorYieldResult',
  'TypedPropertyDescriptor',
  'AsyncIterator',
  'NewableFunction',
  'CallableFunction',
  'PropertyDescriptor'
];
