/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated file by gen_null_arg_tests.rb script -- DO NOT EDIT!

#include "libabckit/include/c/abckit.h"
#include "libabckit/include/c/ir_core.h"
#include "libabckit/include/c/isa/isa_dynamic.h"
#include "libabckit/src/include_v2/c/isa/isa_static.h"

#include "helpers/helpers_mode.h"

#include <gtest/gtest.h>

namespace libabckit::test {

static auto g_isaApiDynamicImp = AbckitGetIsaApiDynamicImpl(ABCKIT_VERSION_RELEASE_1_0_0);

class LibAbcKitWrongModeTestsIsaApiDynamicImpl1 : public ::testing::Test {};

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDelobjprop,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateDelobjprop)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateDelobjprop, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStmodulevar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStmodulevar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStmodulevar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdnan,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLdnan)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdnan, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefinefunc,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateDefinefunc)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateDefinefunc, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStobjbyindex,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideStobjbyindex)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideStobjbyindex, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStobjbyindex,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStobjbyindex)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStobjbyindex, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeDefinefieldbyindex,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCallruntimeDefinefieldbyindex)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeDefinefieldbyindex, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallargs2,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCallargs2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallargs2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGreatereq,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateGreatereq)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateGreatereq, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreateobjectwithexcludedkeys,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCreateobjectwithexcludedkeys)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCreateobjectwithexcludedkeys, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdnull,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLdnull)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdnull, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeStsendablevar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCallruntimeStsendablevar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeStsendablevar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowNotexists,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateThrowNotexists)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateThrowNotexists, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCopyrestargs,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCopyrestargs)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCopyrestargs, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLess,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLess)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLess, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdthisbyname,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLdthisbyname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdthisbyname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdsymbol,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLdsymbol)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdsymbol, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallthisrange,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCallthisrange)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallthisrange, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreateemptyobject,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCreateemptyobject)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCreateemptyobject, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNoteq,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateNoteq)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateNoteq, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateReturn,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateReturn)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateReturn, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdnewtarget,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLdnewtarget)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdnewtarget, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNewlexenvwithname,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateNewlexenvwithname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateNewlexenvwithname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateInc,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateInc)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateInc, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideSupercallarrowrange,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideSupercallarrowrange)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideSupercallarrowrange, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStmodulevar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideStmodulevar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideStmodulevar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCreateobjectwithexcludedkeys,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideCreateobjectwithexcludedkeys)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideCreateobjectwithexcludedkeys, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeWideldsendablevar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCallruntimeWideldsendablevar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeWideldsendablevar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSupercallthisrange,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateSupercallthisrange)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateSupercallthisrange, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTonumeric,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateTonumeric)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateTonumeric, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateApply,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateApply)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateApply, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAsyncfunctionawaituncaught,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateAsyncfunctionawaituncaught)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateAsyncfunctionawaituncaught, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCatchPhi,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCatchPhi)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCatchPhi, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeLdsendableexternalmodulevar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCallruntimeLdsendableexternalmodulevar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeLdsendableexternalmodulevar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeCreateprivateproperty,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCallruntimeCreateprivateproperty)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeCreateprivateproperty, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNot,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateNot)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateNot, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdfalse,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLdfalse)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdfalse, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallarg0,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCallarg0)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallarg0, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideNewlexenvwithname,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideNewlexenvwithname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideNewlexenvwithname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCallrange,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideCallrange)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideCallrange, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbyvaluewithnameset,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStownbyvaluewithnameset)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStownbyvaluewithnameset, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTryldglobalbyname,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateTryldglobalbyname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateTryldglobalbyname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateEq,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateEq)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateEq, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdexternalmodulevar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLdexternalmodulevar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdexternalmodulevar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdinfinity,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLdinfinity)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdinfinity, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbyname,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStownbyname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStownbyname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStownbyindex,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideStownbyindex)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideStownbyindex, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeIstrue,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCallruntimeIstrue)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeIstrue, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateShr2,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateShr2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateShr2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStthisbyvalue,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStthisbyvalue)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStthisbyvalue, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetunmappedargs,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateGetunmappedargs)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateGetunmappedargs, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateResumegenerator,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateResumegenerator)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateResumegenerator, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdlocalmodulevar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideLdlocalmodulevar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideLdlocalmodulevar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSupercallspread,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateSupercallspread)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateSupercallspread, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAsyncgeneratorresolve,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateAsyncgeneratorresolve)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateAsyncgeneratorresolve, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAsyncfunctionenter,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateAsyncfunctionenter)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateAsyncfunctionenter, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeIsfalse,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCallruntimeIsfalse)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeIsfalse, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAshr2,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateAshr2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateAshr2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdlexvar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLdlexvar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdlexvar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbyvalue,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStownbyvalue)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStownbyvalue, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdsuperbyvalue,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLdsuperbyvalue)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdsuperbyvalue, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStrictnoteq,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStrictnoteq)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStrictnoteq, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideNewobjrange,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideNewobjrange)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideNewobjrange, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideGetmodulenamespace,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideGetmodulenamespace)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideGetmodulenamespace, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdprivateproperty,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLdprivateproperty)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdprivateproperty, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStprivateproperty,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStprivateproperty)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStprivateproperty, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeDefinefieldbyvalue,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCallruntimeDefinefieldbyvalue)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeDefinefieldbyvalue, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeNotifyconcurrentresult,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCallruntimeNotifyconcurrentresult)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeNotifyconcurrentresult, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdundefined,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLdundefined)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdundefined, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSupercallarrowrange,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateSupercallarrowrange)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateSupercallarrowrange, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowDeletesuperproperty,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateThrowDeletesuperproperty)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateThrowDeletesuperproperty, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdfunction,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLdfunction)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdfunction, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowIfsupernotcorrectcall,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateThrowIfsupernotcorrectcall)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateThrowIfsupernotcorrectcall, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrow,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateThrow)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateThrow, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreatearraywithbuffer,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCreatearraywithbuffer)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCreatearraywithbuffer, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSetgeneratorstate,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateSetgeneratorstate)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateSetgeneratorstate, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateIsfalse,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateIsfalse)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateIsfalse, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefinemethod,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateDefinemethod)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateDefinemethod, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNewobjapply,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateNewobjapply)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateNewobjapply, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowUndefinedifholewithname,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateThrowUndefinedifholewithname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateThrowUndefinedifholewithname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdthis,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLdthis)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdthis, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateIf,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateIf)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateIf, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallrange,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCallrange)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallrange, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStglobalvar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStglobalvar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStglobalvar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallthis0,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateCallthis0)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallthis0, true);
}

}  // namespace libabckit::test