/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated file by gen_null_arg_tests.rb script -- DO NOT EDIT!

#include "libabckit/include/c/abckit.h"
#include "libabckit/include/c/ir_core.h"
#include "libabckit/include/c/isa/isa_dynamic.h"
#include "libabckit/src/include_v2/c/isa/isa_static.h"

#include "helpers/helpers_mode.h"

#include <gtest/gtest.h>

namespace libabckit::test {

static auto g_isaApiDynamicImp = AbckitGetIsaApiDynamicImpl(ABCKIT_VERSION_RELEASE_1_0_0);

class LibAbcKitWrongModeTestsIsaApiDynamicImpl0 : public ::testing::Test {};

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallthis1,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCallthis1)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallthis1, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetnextpropname,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateGetnextpropname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateGetnextpropname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateMod2,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateMod2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateMod2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGettemplateobject,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateGettemplateobject)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateGettemplateobject, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateIsin,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateIsin)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateIsin, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeTopropertykey,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCallruntimeTopropertykey)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeTopropertykey, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLesseq,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateLesseq)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLesseq, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTestin,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateTestin)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateTestin, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetasynciterator,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateGetasynciterator)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateGetasynciterator, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreatePoplexenv,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreatePoplexenv)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreatePoplexenv, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStthisbyname,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateStthisbyname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStthisbyname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeDefinesendableclass,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCallruntimeDefinesendableclass)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeDefinesendableclass, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDiv2,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateDiv2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateDiv2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStlexvar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateWideStlexvar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideStlexvar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdpatchvar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateWideLdpatchvar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideLdpatchvar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeCallinit,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCallruntimeCallinit)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeCallinit, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowIfnotobject,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateThrowIfnotobject)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateThrowIfnotobject, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDec,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateDec)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateDec, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetpropiterator,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateGetpropiterator)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateGetpropiterator, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdlexvar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateWideLdlexvar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideLdlexvar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideSupercallthisrange,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateWideSupercallthisrange)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideSupercallthisrange, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdthisbyvalue,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateLdthisbyvalue)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdthisbyvalue, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdlocalmodulevar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateLdlocalmodulevar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdlocalmodulevar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateReturnundefined,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateReturnundefined)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateReturnundefined, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefinefieldbyname,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateDefinefieldbyname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateDefinefieldbyname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdsuperbyname,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateLdsuperbyname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdsuperbyname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdobjbyindex,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateWideLdobjbyindex)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideLdobjbyindex, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdbigint,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateLdbigint)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdbigint, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefinegettersetterbyvalue,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateDefinegettersetterbyvalue)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateDefinegettersetterbyvalue, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStarrayspread,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateStarrayspread)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStarrayspread, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCallthisrange,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateWideCallthisrange)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideCallthisrange, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSetobjectwithproto,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateSetobjectwithproto)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateSetobjectwithproto, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowPatternnoncoercible,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateThrowPatternnoncoercible)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateThrowPatternnoncoercible, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeNewsendableenv,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCallruntimeNewsendableenv)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeNewsendableenv, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSub2,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateSub2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateSub2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeWidenewsendableenv,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCallruntimeWidenewsendableenv)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeWidenewsendableenv, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetresumemode,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateGetresumemode)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateGetresumemode, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCopydataproperties,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCopydataproperties)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCopydataproperties, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefineclasswithbuffer,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateDefineclasswithbuffer)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateDefineclasswithbuffer, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdobjbyvalue,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateLdobjbyvalue)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdobjbyvalue, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallargs3,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCallargs3)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallargs3, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateMul2,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateMul2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateMul2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStpatchvar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateWideStpatchvar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideStpatchvar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreateiterresultobj,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCreateiterresultobj)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCreateiterresultobj, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDebugger,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateDebugger)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateDebugger, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateXor2,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateXor2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateXor2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetmodulenamespace,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateGetmodulenamespace)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateGetmodulenamespace, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateOr2,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateOr2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateOr2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdtrue,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateLdtrue)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdtrue, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLoadString,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateLoadString)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLoadString, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeLdsendablevar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCallruntimeLdsendablevar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeLdsendablevar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreategeneratorobj,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCreategeneratorobj)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCreategeneratorobj, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbynamewithnameset,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateStownbynamewithnameset)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStownbynamewithnameset, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallarg1,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCallarg1)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallarg1, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeWideldsendableexternalmodulevar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCallruntimeWideldsendableexternalmodulevar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeWideldsendableexternalmodulevar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdexternalmodulevar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateWideLdexternalmodulevar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideLdexternalmodulevar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowConstassignment,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateThrowConstassignment)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateThrowConstassignment, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAnd2,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateAnd2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateAnd2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStobjbyvalue,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateStobjbyvalue)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStobjbyvalue, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDynamicimport,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateDynamicimport)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateDynamicimport, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTonumber,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateTonumber)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateTonumber, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAsyncgeneratorreject,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateAsyncgeneratorreject)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateAsyncgeneratorreject, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdobjbyname,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateLdobjbyname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdobjbyname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNewlexenv,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateNewlexenv)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateNewlexenv, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAsyncfunctionreject,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateAsyncfunctionreject)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateAsyncfunctionreject, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStsuperbyvalue,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateStsuperbyvalue)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStsuperbyvalue, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallthis3,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCallthis3)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallthis3, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreateobjectwithbuffer,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCreateobjectwithbuffer)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCreateobjectwithbuffer, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStsuperbyname,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateStsuperbyname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStsuperbyname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNewobjrange,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateNewobjrange)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateNewobjrange, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAdd2,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateAdd2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateAdd2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStobjbyname,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateStobjbyname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStobjbyname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallthis2,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCallthis2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallthis2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreateemptyarray,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCreateemptyarray)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCreateemptyarray, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStlexvar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateStlexvar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStlexvar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGreater,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateGreater)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateGreater, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateShl2,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateShl2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateShl2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefinepropertybyname,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateDefinepropertybyname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateDefinepropertybyname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTypeof,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateTypeof)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateTypeof, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateIstrue,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateIstrue)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateIstrue, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdglobalvar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateLdglobalvar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdglobalvar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateExp,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateExp)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateExp, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNeg,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateNeg)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateNeg, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeLdsendableclass,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCallruntimeLdsendableclass)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeLdsendableclass, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdglobal,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateLdglobal)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdglobal, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSuspendgenerator,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateSuspendgenerator)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateSuspendgenerator, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowUndefinedifhole,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateThrowUndefinedifhole)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateThrowUndefinedifhole, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateGetiterator,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateGetiterator)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateGetiterator, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTrystglobalbyname,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateTrystglobalbyname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateTrystglobalbyname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateAsyncfunctionresolve,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateAsyncfunctionresolve)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateAsyncfunctionresolve, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateInstanceof,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateInstanceof)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateInstanceof, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStricteq,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateStricteq)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStricteq, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbyindex,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateStownbyindex)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStownbyindex, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdhole,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateLdhole)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdhole, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeDefineprivateproperty,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCallruntimeDefineprivateproperty)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeDefineprivateproperty, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreateasyncgeneratorobj,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCreateasyncgeneratorobj)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCreateasyncgeneratorobj, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdobjbyindex,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateLdobjbyindex)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdobjbyindex, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCopyrestargs,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateWideCopyrestargs)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideCopyrestargs, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeWidestsendablevar,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateCallruntimeWidestsendablevar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateCallruntimeWidestsendablevar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideNewlexenv,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateWideNewlexenv)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideNewlexenv, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDelobjprop,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl0, iCreateDelobjprop)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateDelobjprop, true);
}

}  // namespace libabckit::test