pack build-common:
  extends:
    - .npm-pack
    - .linux-vm-shell-task
  variables:
    PACKAGE_DIR: incremental/build-common
  needs: []

publish build-common:
  extends: 
    - .npm-publish
    - .linux-vm-shell-task
  variables:
    PACKAGE_DIR: incremental/build-common