#include "RNOH/PackageProvider.h"
#include "CodegenLibSamplePackage.h"
#include "SamplePackage.h"
#include "generated/RNOHGeneratedPackage.h"

using namespace rnoh;

std::vector<std::shared_ptr<Package>> PackageProvider::getPackages(
    Package::Context ctx) {
  return {
      std::make_shared<RNOHGeneratedPackage>(
          ctx), // generated by codegen-harmony v1 at app build time
      std::make_shared<SamplePackage>(
          ctx), // partially generated by codegen-harmony v2 at app build time
      std::make_shared<CodegenLibSamplePackage>(
          ctx), // partially generate by codegen-harmony-lib at library publish
                // time
  };
}