import mustache from 'mustache';

const TEMPLATE = `
/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 */
{{#reexports}}
export * {{as}}from "{{{from}}}"
{{/reexports}}
`;

const TEMPLATE_EMPTY = `
/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 */

export {}
`;

type Reexport = {
  from: string;
  as?: string;
};

export class IndexTSTemplate {
  private reexports: Reexport[] = [];

  constructor() {}

  addReexport(reexport: Reexport) {
    this.reexports.push(reexport);
    return this;
  }

  build(): string {
    if (this.reexports.length === 0) {
      return mustache.render(TEMPLATE_EMPTY, {});
    }

    return mustache.render(TEMPLATE.trimStart(), {
      reexports: this.reexports.map((reexport) => ({
        from: reexport.from,
        as: reexport.as ? `as ${reexport.as} ` : '',
      })),
    });
  }
}
