import mustache from 'mustache';

const TEMPLATE = `
/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: {{generatorVersion}}
 */
#pragma once

#include "RNOH/ArkTSTurboModule.h"

namespace rnoh {

class JSI_EXPORT {{className}} : public ArkTSTurboModule {
  public:
    {{className}}(const ArkTSTurboModule::Context ctx, const std::string name);
};

} // namespace rnoh
`;

export class TurboModuleHTemplate {
  constructor(private name: string, private generatorVersion: number) {}

  build(): string {
    return mustache.render(TEMPLATE, {
      className: this.name,
      generatorVersion: this.generatorVersion,
    });
  }
}
