import mustache from 'mustache';

const TEMPLATE = `
/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: {{generatorVersion}}
 */
#include "{{className}}.h"

namespace rnoh {
using namespace facebook;

{{className}}::{{className}}(const ArkTSTurboModule::Context ctx, const std::string name) : ArkTSTurboModule(ctx, name) {
    methodMap_ = {
        {{#methods}}
        ARK_{{asyncMarker}}METHOD_METADATA({{name}}, {{argsCount}}),
        {{/methods}}
    };
}

} // namespace rnoh
`;

export type TurboModuleCppTemplateMethod = {
  name: string;
  isAsync: boolean;
  argsCount: number;
};

export class TurboModuleCppTemplate {
  private methods: TurboModuleCppTemplateMethod[] = [];

  constructor(private name: string, private generatorVersion: number) {}

  addMethod(method: TurboModuleCppTemplateMethod) {
    this.methods.push(method);
  }

  build(): string {
    return mustache.render(TEMPLATE, {
      className: this.name,
      generatorVersion: this.generatorVersion,
      methods: this.methods.map((method) => ({
        name: method.name,
        argsCount: method.argsCount,
        asyncMarker: method.isAsync ? 'ASYNC_' : undefined,
      })),
    });
  }
}
